### ISSUE TITLE
Validate TMDb API key upon initialization

### ISSUE THREAD

**Issue by CollinHeist** [CollinHeist/TitleCardMaker#107]
During either preference parsing or TMDbInterface creation, the provided API key should be validated before any requests are made.

**Comment by meisnate12** [comment]
consider checking out [TMDbAPIs](https://github.com/meisnate12/TMDbAPIs) is a python api wrapper i wrote for TMDb itll do alot of the work for you.

**Comment by CollinHeist** [comment]
@meisnate12 That would have been useful before I manually did a lot of the TMDb API stuff! Thank you, I'll look at that.

**Comment by meisnate12** [comment]
It still could simplify a lot of things and save you plenty of work in the future let me know if you have any questions you know where to find me lol
