### ISSUE TITLE
Add feature to delete old cards of a given series

### ISSUE THREAD

**Issue by CollinHeist** [CollinHeist/TitleCardMaker#116]
If the user changes their filename format, a bunch of duplicate/old cards will be leftover. Add some fixer functionality to delete those cards, perhaps:

```console
# python fixer.py --delete-cards DIRECTORY [DIRECTORY_2] [extension=jpg]
```

Which would glob for images within the specified directories and delete them. Any title cards that are "correct" will be remade the next time the Maker is ran.

**Comment by Wdvh** [comment]
maybe add "delete unmanaged sources and/or cards" functionality to it. could come in handy if you download some show and after a few episodes you decide its not for you and want to get rid of it.
