### ISSUE TITLE
Unraid template is incorrect

### ISSUE THREAD

**Issue by 666dsa666** [CollinHeist/TitleCardMaker#173]
Sorry for this,

As you got the app in the unraid app store you'll probably get a few bugs report from new users like me.

I've had 3 so far, I'll create one for each
**Describe the bug**
Bug 1 : Error in the app definition

- Default tag is incorrect (://github.com/CollinHeist/TitleCardMaker) instead of "master"
- Master repository is "https:master" instead of "collinheist/titlecardmaker:master"
- Same with develop : "https:develop" instead of "collinheist/titlecardmaker:develop"

**To Reproduce**
Bug 1:
1. Use Unraid
2. Use Community App Store
3. Try to install the app

**Expected behavior**
Default value should be valid

**Screenshots**
![image](https://user-images.githubusercontent.com/11072018/173386500-69898111-6650-4a0e-b289-855d083d2c7a.png)
![image](https://user-images.githubusercontent.com/11072018/173386522-46cd6120-b1fb-4343-a144-bb393401d322.png)

**Config File**
Not needed

**Series YAML File(s)**
Not needed

**Desktop of the machine running the TitleCardMaker:**
Unraid 6.10.2

**ImageMagick:**
N/A

**Additional context**
App Store version 2022.05.15

**Comment by CollinHeist** [comment]
Looks like the config XML doesn't want the full GitHub URL, thanks for catching that. As noted above, I have fixed this. I'll keep open until it's pulled into the CA (should be at most 2 hours)

**Comment by CollinHeist** [comment]
Looks like the fix has been pulled in. Thanks again for catching this!

![Screen Shot 2022-06-13 at 1 32 08 PM](https://user-images.githubusercontent.com/17693271/173430504-f5ca3fb5-361a-4d8f-b7fc-39a416172490.jpg)
