### ISSUE TITLE
Poster generation hang if poster exists (unraid related ?)

### ISSUE THREAD

**Issue by 666dsa666** [CollinHeist/TitleCardMaker#175]
**Describe the bug**
Poster generation hang indefinitely if poster already exists in unraid
First generation works fine
Deleting posters allow for script to run without issues once

**To Reproduce**
Using Unraid
1. Set preferences.yml and tv.yml using wiki
2. Start docker (from CA store)
3. Poster generation works
4. Restart docker
5. Poster generation hangs

**Expected behavior**
Poster should be checked and not regenerated if already exists (and no picture/episode name update)
If poster generation is needed, it should be deleting or writing over existing files

**Screenshots**
![image](https://user-images.githubusercontent.com/11072018/173388715-4456be48-d99b-4f9e-a236-e7e94ef7e0c5.png)
![image](https://user-images.githubusercontent.com/11072018/173388825-114265f6-ec2b-49b7-9ba7-dc1568d4d981.png)

**Config File**

**Series YAML File(s)**
[tv.txt](https://github.com/CollinHeist/TitleCardMaker/files/8892405/tv.txt)

**Desktop of the machine running the TitleCardMaker:**
Unraid 6.10.2

**ImageMagick:**
N/A

**Additional context**

**Comment by CollinHeist** [comment]
So are you generating season posters (they'd be labelled like `Season1.jpg`) or title cards? And could you paste your log file(s) from the `logs` directory?

**Comment by 666dsa666** [comment]
> So are you generating season posters (they'd be labelled like `Season1.jpg`) or title cards? And could you paste your log file(s) from the `logs` directory?

Title cards as season posters doesn't seems to be working atm.

I checked logs and think I understand what happens.
[logs.txt](https://github.com/CollinHeist/TitleCardMaker/files/8892955/logs.txt)
From my understanding it's not hanging but waiting for the next run.

It might be an unraid issue as logs show : 
usermod: no changes
[INFO] Read preference file "/config/preferences.yml"
Creating Title Cards for "Mr. Robot":    0%|          | 0/1 [00:00, ?it/s] 
   0%|          | 0/45 [00:00, ?it/s]

Which should probably be replaced by 
Starting first run in 17243 seconds

**Comment by CollinHeist** [comment]
> Title cards as season posters doesn't seems to be working atm.

Based off your screenshot, looks like the title cards were generated as expected. If you want it to make season posters there needs to be files like `season1.jpg` in the source directory, so it can use those. That's not covered in the setup tutorial

> From my understanding it's not hanging but waiting for the next run.

So looking at the log, you're correct - the Maker is running, seeing nothing else to do, and holding for ~4 hours. That seems expected, given the cards are already created.

> It might be an unraid issue as logs show :

Yeah I am not sure why the logs would still show that old message, not sure where Unraid gets the log from.

**Comment by 666dsa666** [comment]
I've added this path for easier access to logs : 
/maker/logs   ->   /mnt/disks/ua_docker/appdata/TitleCardMaker/Logs/
This make access to logs possible through unraid "appdata" share.
This can also be done by writing logs in the config folder but the cleanest way would be to have the default path to be : 
/config = *appdata*/TitleCardMaker/config
/maker/logs = *appdata*/TitleCardMaker/logs

I think I misunderstood how the season poster was generated and it does indeed seems to be working using the color error fix and the right files at the right places.

**Comment by CollinHeist** [comment]
> /config = appdata/TitleCardMaker/config
/maker/logs = appdata/TitleCardMaker/logs

Very good idea, I have added that to the template config [here](https://github.com/CollinHeist/UnraidConfig/commit/18f9a1427e68ec2bb59c3d4a67f4cfe2e33773ca) - thanks!

> I think I misunderstood how the season poster was generated and it does indeed seems to be working using the color error fix and the right files at the right places.

Okay good to hear, I'll close this for now 👍🏻
