### ISSUE TITLE
Translation is not taken into account

### ISSUE THREAD

**Issue by 666dsa666** [CollinHeist/TitleCardMaker#176]
**Describe the bug**
Setting translations settings does not seems to produce translated episode names on posters

**To Reproduce**
Use 
`    translation:
      language: fr
      key: french_title`
On Mr. ROBOT (tv.yml attached)

**Expected behavior**
Episode name sjould be in french ( or any set language)

**Screenshots**
![image](https://user-images.githubusercontent.com/11072018/173389943-b6b9bc86-142f-4131-86ad-7877c72ee6e9.png)
![image](https://user-images.githubusercontent.com/11072018/173390007-28410063-2f0d-44e8-a51a-4cd4f312de65.png)
TMDB : 
![image](https://user-images.githubusercontent.com/11072018/173390125-54060e37-2d39-49ce-84a5-836e26c0235b.png)
Requests are made to TMDB : 
![image](https://user-images.githubusercontent.com/11072018/173390708-85d8321d-c250-4313-8701-682ed300c8bf.png)

**Config File**

**Series YAML File(s)**
[tv.txt](https://github.com/CollinHeist/TitleCardMaker/files/8892443/tv.txt)

**Desktop of the machine running the TitleCardMaker:**
Unraid 6.10.2

**ImageMagick:**
N/A

**Additional context**

**Comment by CollinHeist** [comment]
If you want the french titles to be utilized, you need to specify the translation key as `preferred_title`, otherwise it will just download the title and place them in the datafile.

See [here](https://github.com/CollinHeist/TitleCardMaker/wiki/Data-Files#preferred-title) for more details

**Comment by CollinHeist** [comment]
You're good! I updated the Wiki so it's more clear
