### ISSUE TITLE
BUG - PermissionError: [Errno 13] Permission denied - UnRaid

### ISSUE THREAD

**Issue by subasically** [CollinHeist/TitleCardMaker#182]
### Installation

Docker - master tag

### Describe the Bug

I am getting a PermissionError when I try to run the app.
`usermod: no changes
[INFO] Read preference file "/config/preferences.yml"
Reading tv.yml:    0%|          | 0/1 [00:00, ?it/s]
Traceback (most recent call last):                              
  File "/maker/main.py", line 135, in <module>    
    run()
  File "/maker/main.py", line 130, in run
    tcm.run()
  File "/maker/modules/Manager.py", line 259, in run
    self.check_sonarr_for_new_episodes()
  File "/maker/modules/Manager.py", line 146, in check_sonarr_for_new_episodes
    show.query_sonarr(self.sonarr_interface)
  File "/maker/modules/Show.py", line 416, in query_sonarr
    self.file_interface.add_many_entries(new_episodes)
  File "/maker/modules/DataFileInterface.py", line 263, in add_many_entries
    self.sort_and_write(yaml)
  File "/maker/modules/DataFileInterface.py", line 103, in sort_and_write
    self.__write_data(yaml)
  File "/maker/modules/DataFileInterface.py", line 79, in __write_data
    with self.file.open('w', encoding='utf-8') as file_handle:
  File "/usr/local/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/local/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
PermissionError: [Errno 13] Permission denied: '/config/source/Mr. Robot (2015)/data.yml'

** Press ANY KEY to close this window ** `

My setup:
![Docker_UpdateContainer_xmlTemplate=edit__boot_config_plugins_dockerMan_templates-user_my-TitleCardMaker xml](https://user-images.githubusercontent.com/26078024/173595247-1c580b20-fc38-43fb-a06c-1964d0a9e06e.png)

### Steps to reproduce the behavior

1. 
2.
...

### Preference File

```yaml
options:
  source: /config/source/
  series: /config/tv.yml

archive:
  path: /config/archives/
  
plex:
  url: http://my-ip:32400/
  token: 1234

sonarr:
  url: http://my-ip:8989/api/v3/
  api_key: 2345

tmdb:
  api_key: 3456
```

### Debug Log

[INFO] [22-06-14 09:01:16] Read preference file "/config/preferences.yml" [DEBUG] [22-06-14 09:01:16] Using "" ImageMagick command prefix [INFO] [22-06-14 09:01:18] Added 47 episodes to "Mr. Robot (2015)"

**Comment by subasically** [comment]
My folder structure
<img width="1517" alt="image" src="https://user-images.githubusercontent.com/26078024/173597214-3d652008-ca85-4c5e-9411-2b48579422c0.png">

**Comment by CollinHeist** [comment]
Must not have permission to make a `Mr. Robot (2015)` folder in `source`, can you do a set the permissions of `source` and `logs` to the GID/UID of the Maker?

**Comment by subasically** [comment]
I fixed the permission issue by changing the UID to 99 and GID to 100. All my other containers are using those ids.
I also updated the Source Directory under show more settings.
![Docker_UpdateContainer_xmlTemplate=edit__boot_config_plugins_dockerMan_templates-user_my-TitleCardMaker xml (3)](https://user-images.githubusercontent.com/26078024/173625937-859427f2-e4d9-475d-8a56-5f9c217a7de8.png)

Now I am seeing 
[ERROR] Library "TV" was not found in Plex
[ERROR] Library "Anime" was not found in Plex

**Comment by CollinHeist** [comment]
Your series YAML file (`tv.yml`) has a libraries section, and those library names need to match what you have in Plex. So yours must look like:

```yaml
libraries:
  TV:
    path: # some path here
  
  Anime:
    path: # some path here
```

But you need to change `TV` and `Anime` to match the actual names in Plex. See [here](https://github.com/CollinHeist/TitleCardMaker/wiki/Series-YAML-Files#libraries) for more.

**Comment by subasically** [comment]
> Your series YAML file (`tv.yml`) has a libraries section, and those library names need to match what you have in Plex. So yours must look like:
> 
> ```yaml
> libraries:
>   TV:
>     path: # some path here
>   
>   Anime:
>     path: # some path here
> ```
> 
> But you need to change `TV` and `Anime` to match the actual names in Plex. See [here](https://github.com/CollinHeist/TitleCardMaker/wiki/Series-YAML-Files#libraries) for more.

I got the library matching my Plex names.
<img width="700" alt="image" src="https://user-images.githubusercontent.com/26078024/173660603-1a3f90fa-54f9-45be-a414-2dbd0bcda062.png">

Current issue is that it never gets past Creating Title Cards and just hangs there
<img width="682" alt="image" src="https://user-images.githubusercontent.com/26078024/173660722-b409d9c1-9852-435c-90fe-502ac879b0d7.png">
