### ISSUE TITLE
BUG - Generated images do not have background, just text

### ISSUE THREAD

**Issue by subasically** [CollinHeist/TitleCardMaker#186]
### Installation

Docker - master tag

### Describe the Bug

The generated images only have the name, season, and episode number.
The background is missing
![Demon Slayer - Kimetsu no Yaiba (2019) - S01E08](https://user-images.githubusercontent.com/26078024/173690706-cedf34f6-c780-4424-a0ea-636c1182e437.jpeg)

### Expected Behavior

Generated images have episode cards with text on top.

### Preference File

```yaml
options:
  source: /config/source/
  series: /config/tv.yml
  source_priority: plex
  zero_pad_seasons: true

# archive:
#   path: /config/archives/
  
plex:
  url: http://10.10.10.5:32400/
  token: TOKEN
  
sonarr:
  url: http://10.10.10.5:8989/api/v3/
  api_key: TOKEN

tmdb:
  api_key: TOKEN
```

### Series YAML

```yaml
libraries:
  TV Shows:
    path: /TV/
    # plex_name: "TV Shows"

series:
  Demon Slayer - Kimetsu no Yaiba:
    year: 2019
    library: TV Shows
    media_directory: /TV/Demon Slayer - Kimetsu no Yaiba (2019) [imdb-tt9335498]
    translation:
      language: ja
      key: kanji
    seasons:
      1: Finding my Life's Purpose
      2: Mugen Train
      3: Entertainment District
```

### Debug Log

[INFO] [22-06-14 16:10:17] Read preference file "/config/preferences.yml" [DEBUG] [22-06-14 16:10:19] Using "" ImageMagick command prefix [INFO] [22-06-14 16:10:21] Added 55 episodes to "Demon Slayer - Kimetsu no Yaiba (2019)" [DEBUG] [22-06-14 16:10:21] Adding "鬼滅の刃 無限列車編 映画" to "kanji" of "Demon Slayer - Kimetsu no Yaiba (2019)" [DEBUG] [22-06-14 16:10:21] Adding "中高一貫！！キメツ学園物語 バレンタイン編 第一話" to "kanji" of "Demon Slayer - Kimetsu no Yaiba (2019)" [DEBUG] [22-06-14 16:10:22] Adding "中高一貫！！キメツ学園物語 バレンタイン編 第二話" to "kanji" of "Demon Slayer - Kimetsu no Yaiba (2019)" [DEBUG] [22-06-14 16:10:22] Adding "中高一貫！！キメツ学園物語 バレンタイン編 第三話" to "kanji" of "Demon Slayer - Kimetsu no Yaiba (2019)" [DEBUG] [22-06-14 16:10:23] Adding "中高一貫！！キメツ学園物語 バレンタイン編 第四話" to "kanji" of "Demon Slayer - Kimetsu no Yaiba (2019)" [DEBUG] [22-06-14 16:10:23] Adding "残酷" to "kanji" of "Demon Slayer - Kimetsu no Yaiba (2019)" [DEBUG] [22-06-14 16:10:23] Adding "育手・鱗滝左近次" to "kanji" of "Demon Slayer - Kimetsu no Yaiba (2019)" [DEBUG] [22-06-14 16:10:24] Adding "錆兎と真菰" to "kanji" of "Demon Slayer - Kimetsu no Yaiba (2019)" [DEBUG] [22-06-14 16:10:24] Adding "最終選別" to "kanji" of "Demon Slayer - Kimetsu no Yaiba (2019)" [DEBUG] [22-06-14 16:10:25] Adding "己の鋼" to "kanji" of "Demon Slayer - Kimetsu no Yaiba (2019)" [DEBUG] [22-06-14 16:10:25] Adding "鬼を連れた剣士" to "kanji" of "Demon Slayer - Kimetsu no Yaiba (2019)" [DEBUG] [22-06-14 16:10:26] Adding "鬼舞辻無慘" to "kanji" of "Demon Slayer - Kimetsu no Yaiba (2019)" [DEBUG] [22-06-14 16:10:26] Adding "幻惑の血の香り" to "kanji" of "Demon Slayer - Kimetsu no Yaiba (2019)" [DEBUG] [22-06-14 16:10:27] Adding "手毬鬼と矢印鬼" to "kanji" of "Demon Slayer - Kimetsu no Yaiba (2019)" [DEBUG] [22-06-14 16:10:27] Adding "ずっと一緒にいる" to "kanji" of "Demon Slayer - Kimetsu no Yaiba (2019)" [DEBUG] [22-06-14 16:10:27] Adding "鼓の屋敷" to "kanji" of "Demon Slayer - Kimetsu no Yaiba (2019)" [DEBUG] [22-06-14 16:10:28] Adding "猪は牙を剥き 善逸は眠る" to "kanji" of "Demon Slayer - Kimetsu no Yaiba (2019)" [DEBUG] [22-06-14 16:10:28] Adding "命より大事なもの" to "kanji" of "Demon Slayer - Kimetsu no Yaiba (2019)" [DEBUG] [22-06-14 16:10:29] Adding "藤の花の家紋の家" to "kanji" of "Demon Slayer - Kimetsu no Yaiba (2019)" [DEBUG] [22-06-14 16:10:29] Adding "那田蜘蛛山" to "kanji" of "Demon Slayer - Kimetsu no Yaiba (2019)" [DEBUG] [22-06-14 16:10:30] Adding "自分ではない誰かを前へ" to "kanji" of "Demon Slayer - Kimetsu no Yaiba (2019)" [DEBUG] [22-06-14 16:10:30] Adding "ひとつのことを極め抜け" to "kanji" of "Demon Slayer - Kimetsu no Yaiba (2019)" [DEBUG] [22-06-14 16:10:30] Adding "偽物の絆" to "kanji" of "Demon Slayer - Kimetsu no Yaiba (2019)" [DEBUG] [22-06-14 16:10:31] Adding "ヒノカミ" to "kanji" of "Demon Slayer - Kimetsu no Yaiba (2019)" [DEBUG] [22-06-14 16:10:31] Adding "寄せ集めの家族" to "kanji" of "Demon Slayer - Kimetsu no Yaiba (2019)" [DEBUG] [22-06-14 16:10:32] Adding "隊律違反" to "kanji" of "Demon Slayer - Kimetsu no Yaiba (2019)" [DEBUG] [22-06-14 16:10:32] Adding "お館様" to "kanji" of "Demon Slayer - Kimetsu no Yaiba (2019)" [DEBUG] [22-06-14 16:10:33] Adding "柱合会議" to "kanji" of "Demon Slayer - Kimetsu no Yaiba (2019)" [DEBUG] [22-06-14 16:10:33] Adding "機能回復訓練" to "kanji" of "Demon Slayer - Kimetsu no Yaiba (2019)" [DEBUG] [22-06-14 16:10:33] Adding "継子・栗花落カナヲ" to "kanji" of "Demon Slayer - Kimetsu no Yaiba (2019)" [DEBUG] [22-06-14 16:10:34] Adding "新たなる任務" to "kanji" of "Demon Slayer - Kimetsu no Yaiba (2019)" [DEBUG] [22-06-14 16:10:34] Adding "炎柱・煉獄杏寿郎" to "kanji" of "Demon Slayer - Kimetsu no Yaiba (2019)" [DEBUG] [22-06-14 16:10:35] Adding "深い眠り" to "kanji" of "Demon Slayer - Kimetsu no Yaiba (2019)" [DEBUG] [22-06-14 16:10:36] Adding "本当なら" to "kanji" of "Demon Slayer - Kimetsu no Yaiba (2019)" [DEBUG] [22-06-14 16:10:42] Adding "侮辱" to "kanji" of "Demon Slayer - Kimetsu no Yaiba (2019)" [DEBUG] [22-06-14 16:10:43] Adding "前へ！" to "kanji" of "Demon Slayer - Kimetsu no Yaiba (2019)" [DEBUG] [22-06-14 16:10:43] Adding "猗窩座" to "kanji" of "Demon Slayer - Kimetsu no Yaiba (2019)" [DEBUG] [22-06-14 16:10:44] Adding "心を燃やせ" to "kanji" of "Demon Slayer - Kimetsu no Yaiba (2019)" [DEBUG] [22-06-14 16:10:44] Adding "音柱・宇髄天元" to "kanji" of "Demon Slayer - Kimetsu no Yaiba (2019)" [DEBUG] [22-06-14 16:10:45] Adding "遊郭潜入" to "kanji" of "Demon Slayer - Kimetsu no Yaiba (2019)" [DEBUG] [22-06-14 16:10:45] Adding "何者？" to "kanji" of "Demon Slayer - Kimetsu no Yaiba (2019)" [DEBUG] [22-06-14 16:10:46] Adding "今夜" to "kanji" of "Demon Slayer - Kimetsu no Yaiba (2019)" [DEBUG] [22-06-14 16:10:46] Adding "ド派手に行くぜ‼" to "kanji" of "Demon Slayer - Kimetsu no Yaiba (2019)" [DEBUG] [22-06-14 16:10:47] Adding "重なる記憶" to "kanji" of "Demon Slayer - Kimetsu no Yaiba (2019)" [DEBUG] [22-06-14 16:10:47] Adding "変貌" to "kanji" of "Demon Slayer - Kimetsu no Yaiba (2019)" [DEBUG] [22-06-14 16:10:48] Adding "集結" to "kanji" of "Demon Slayer - Kimetsu no Yaiba (2019)" [DEBUG] [22-06-14 16:10:48] Adding "上弦の鬼を倒したら" to "kanji" of "Demon Slayer - Kimetsu no Yaiba (2019)" [DEBUG] [22-06-14 16:10:49] Adding "絶対諦めない" to "kanji" of "Demon Slayer - Kimetsu no Yaiba (2019)" [DEBUG] [22-06-14 16:10:49] Adding "何度生まれ変わっても" to "kanji" of "Demon Slayer - Kimetsu no Yaiba (2019)" [DEBUG] [22-06-14 16:10:54] Converted logo for "Demon Slayer - Kimetsu no Yaiba (2019)" from .svg to .png [DEBUG] [22-06-14 16:10:54] Downloaded logo for "Demon Slayer - Kimetsu no Yaiba (2019)" [DEBUG] [22-06-14 16:11:24] Created card "/TV/Demon Slayer - Kimetsu no Yaiba (2019) [imdb-tt9335498]/Season 01/Demon Slayer - Kimetsu no Yaiba (2019) - S01E08.jpg" [DEBUG] [22-06-14 16:11:31] Created card "/TV/Demon Slayer - Kimetsu no Yaiba (2019) [imdb-tt9335498]/Season 01/Demon Slayer - Kimetsu no Yaiba (2019) - S01E09.jpg" [DEBUG] [22-06-14 16:11:37] Created card "/TV/Demon Slayer - Kimetsu no Yaiba (2019) [imdb-tt9335498]/Season 01/Demon Slayer - Kimetsu no Yaiba (2019) - S01E10.jpg" [DEBUG] [22-06-14 16:11:44] Created card "/TV/Demon Slayer - Kimetsu no Yaiba (2019) [imdb-tt9335498]/Season 01/Demon Slayer - Kimetsu no Yaiba (2019) - S01E11.jpg" [DEBUG] [22-06-14 16:11:51] Created card "/TV/Demon Slayer - Kimetsu no Yaiba (2019) [imdb-tt9335498]/Season 02/Demon Slayer - Kimetsu no Yaiba (2019) - S02E04.jpg" [DEBUG] [22-06-14 16:11:58] Created card "/TV/Demon Slayer - Kimetsu no Yaiba (2019) [imdb-tt9335498]/Season 02/Demon Slayer - Kimetsu no Yaiba (2019) - S02E05.jpg" [DEBUG] [22-06-14 16:12:05] Created card "/TV/Demon Slayer - Kimetsu no Yaiba (2019) [imdb-tt9335498]/Season 02/Demon Slayer - Kimetsu no Yaiba (2019) - S02E06.jpg" [DEBUG] [22-06-14 16:12:12] Created card "/TV/Demon Slayer - Kimetsu no Yaiba (2019) [imdb-tt9335498]/Season 02/Demon Slayer - Kimetsu no Yaiba (2019) - S02E07.jpg" [DEBUG] [22-06-14 16:12:19] Created card "/TV/Demon Slayer - Kimetsu no Yaiba (2019) [imdb-tt9335498]/Season 03/Demon Slayer - Kimetsu no Yaiba (2019) - S03E01.jpg" [DEBUG] [22-06-14 16:12:26] Created card "/TV/Demon Slayer - Kimetsu no Yaiba (2019) [imdb-tt9335498]/Season 03/Demon Slayer - Kimetsu no Yaiba (2019) - S03E02.jpg" [DEBUG] [22-06-14 16:12:34] Created card "/TV/Demon Slayer - Kimetsu no Yaiba (2019) [imdb-tt9335498]/Season 03/Demon Slayer - Kimetsu no Yaiba (2019) - S03E03.jpg" [DEBUG] [22-06-14 16:12:42] Created card "/TV/Demon Slayer - Kimetsu no Yaiba (2019) [imdb-tt9335498]/Season 03/Demon Slayer - Kimetsu no Yaiba (2019) - S03E04.jpg" [DEBUG] [22-06-14 16:12:50] Created card "/TV/Demon Slayer - Kimetsu no Yaiba (2019) [imdb-tt9335498]/Season 03/Demon Slayer - Kimetsu no Yaiba (2019) - S03E05.jpg" [DEBUG] [22-06-14 16:12:57] Created card "/TV/Demon Slayer - Kimetsu no Yaiba (2019) [imdb-tt9335498]/Season 03/Demon Slayer - Kimetsu no Yaiba (2019) - S03E06.jpg" [DEBUG] [22-06-14 16:13:05] Created card "/TV/Demon Slayer - Kimetsu no Yaiba (2019) [imdb-tt9335498]/Season 03/Demon Slayer - Kimetsu no Yaiba (2019) - S03E07.jpg" [DEBUG] [22-06-14 16:13:12] Created card "/TV/Demon Slayer - Kimetsu no Yaiba (2019) [imdb-tt9335498]/Season 03/Demon Slayer - Kimetsu no Yaiba (2019) - S03E08.jpg" [DEBUG] [22-06-14 16:13:19] Created card "/TV/Demon Slayer - Kimetsu no Yaiba (2019) [imdb-tt9335498]/Season 03/Demon Slayer - Kimetsu no Yaiba (2019) - S03E09.jpg" [DEBUG] [22-06-14 16:13:26] Created card "/TV/Demon Slayer - Kimetsu no Yaiba (2019) [imdb-tt9335498]/Season 03/Demon Slayer - Kimetsu no Yaiba (2019) - S03E10.jpg" [DEBUG] [22-06-14 16:13:33] Created card "/TV/Demon Slayer - Kimetsu no Yaiba (2019) [imdb-tt9335498]/Season 03/Demon Slayer - Kimetsu no Yaiba (2019) - S03E11.jpg" [INFO] [22-06-14 16:13:33] Wrote missing assets to "missing.yml" [INFO] [22-06-14 16:13:33] Starting first run in 6386 seconds

**Comment by CollinHeist** [comment]
This has something to do with the episodes not having source images in Plex. I've seen it before, but never been able to pin down a cause. Could you attach `s1e8.jpg` from the Demon Slayer source directory?

Is it all episodes for this series? Or "random" ones?

**Comment by CollinHeist** [comment]
Is it possible for you to set the machine running TCM to a trusted device within your Plex server, delete one of those source images (like Demon Slayer `s1e1.jpg`) and then re-run the Maker?

**Comment by subasically** [comment]
I can try that once I'm back at my computer.

**Comment by CollinHeist** [comment]
Alright I've found the error, pushing a fix now and I'll close this issue when it's merged

**Comment by subasically** [comment]
> Alright I've found the problem, pushing a fix now and I'll close this issue when it's merged

Thanks!
