### ISSUE TITLE
Allow TMDb and TVDb ID's to be manually specified

### ISSUE THREAD

**Issue by CollinHeist** [CollinHeist/TitleCardMaker#200]
ID's for either a series or episode should be allowed within series YAML or data files.

```yaml
tvdb_id: 01234
tmdb_id: 43210
```

**Comment by CollinHeist** [comment]
So, confusingly, TMDb doesn't actually use the TMDb ID for any API requests; so storing that is useless. However, IMDb IDs' can also be queried so those should be used instead

**Comment by meisnate12** [comment]
TMDb use TMDb IDs all the time in requests

**Comment by CollinHeist** [comment]
I should have been more clear, it doesn’t use the _episode_ ID’s for anything, as far as I can tell.
