### ISSUE TITLE
Handle non /api/v3/ Sonarr URL's

### ISSUE THREAD

**Issue by CollinHeist** [CollinHeist/TitleCardMaker#207]
It's cumbersome to force the user to specify the Sonarr URL as `http://ip:port/api/v3/`, as this isn't intuitive, nor truly necessary.

TCM should parse any valid URL, API endpoint or not.

**Comment by meisnate12** [comment]
Not sure how you're making the sonarr calls but I also made an api wrapper for that although it's no where near as complete and my tmdb api is check out ArrApi
