### ISSUE TITLE
[Wiki Typo] Should read tautulli, not tautull

### ISSUE THREAD

**Issue by Droppisalt** [CollinHeist/TitleCardMaker#235]
On [this](https://github.com/CollinHeist/TitleCardMaker/wiki/Tautulli-Integration#non-docker) page, the command should be changed from:
$ pipenv run python main.py --run --tautulli-update-list "/Documents/tautulli/update.txt" --**tautull-update-frequency** 1m
to:
$ pipenv run python main.py --run --tautulli-update-list "/Documents/tautulli/update.txt" --**tautulli-update-frequency** 1m

**Comment by CollinHeist** [comment]
Fixed - thank you!
