### ISSUE TITLE
Handling too long titles

### ISSUE THREAD

**Issue by JakobTischler** [CollinHeist/TitleCardMaker#249]
**Is your feature request related to a problem? Please describe.**
If the title of an episode is too long, it _might_ lead to the text being cut off at the image edges. Example:
![Covert Affairs (2010) - S01E08 - What Is and What Should Never Be](https://user-images.githubusercontent.com/748857/185989542-6b763606-2bd1-450e-8696-0573781d64e0.jpg)

I've tried both actual line breaks (by putting the episode title in quotes", and hard line breaks like `\n`. Neither work.

**Describe the solution you'd like**
Optimally, an automatic solution where the script would measure the text width and cut it half at the appropriate position (any spacing character that's closest to the mathematical center of the text, i.e. counting characters). Accordingly, the Y position would need to be adjusted upwards.

**Describe alternatives you've considered**
Allow for manual line breaks in the show's `data.yml` file. Parsing the the title to check for how many lines exist would allow for the Y offset towards the top.

---

_In general, I'd like to highjack this post to thank you for this tool. It seems to be *very* well thought out, something I can really appreciate. I love how clean the usage feels even though there seem to be a gazillion options. Great job!_

**Comment by JakobTischler** [comment]
Small update: there seems to be _some_ automatic line breaking already? But for some texts it's still not breaking correctly.

Good line break:
![Eastbound   Down (2009) - S01E04 - Chapter 4 - Kenny’s Pitching Clinic](https://user-images.githubusercontent.com/748857/185994701-6e40e396-67f6-47fc-89b2-d0d115c015c6.jpg)

"A for Effort" line break:
![Eastbound   Down (2009) - S01E05 - Chapter 5 - Beginning A New Audio Book](https://user-images.githubusercontent.com/748857/185994838-a3a8b56f-0de1-4532-8613-a5f531899bb9.jpg)

**Comment by CollinHeist** [comment]
Hey, so the automatic line breaking uses that card's _default_ font to determine how many after how characters to attempt a split. You can either adjust the font size of your custom font (in an attempt to get more accurate splitting and avoid overflow), or you can set a [manually specified title](https://github.com/CollinHeist/TitleCardMaker/wiki/Data-Files#title) to avoid this.

And finally you can also "manually" make the correct card with the [mini maker](https://github.com/CollinHeist/TitleCardMaker/wiki/Using-the-Mini-Maker)

**Comment by CollinHeist** [comment]
Oh and I forgot to mention, in the 2nd and 3rd examples you set, if you assign a custom [episode text format](https://github.com/CollinHeist/TitleCardMaker/wiki/Series-YAML-Files#episode-text-format) in your case
```yaml
episode_text_format: "Chapter {episode_number}"
```
Then TCM will adjust the titles to remove that prefix text, making your titles shorter like `Kenny's Pitching Clinic` which can help the splitting be more accurate

**Comment by JakobTischler** [comment]
> Hey, so the automatic line breaking uses that card's _default_ font to determine how many after how characters to attempt a split. You can either adjust the font size of your custom font (in an attempt to get more accurate splitting and avoid overflow), or you can set a [manually specified title](https://github.com/CollinHeist/TitleCardMaker/wiki/Data-Files#title) to avoid this.

Ah, that makes sense. Thanks for the info. (Should have just opened those detail spoiler boxes...)

---

> if you assign a custom [episode text format](https://github.com/CollinHeist/TitleCardMaker/wiki/Series-YAML-Files#episode-text-format) in your case ...

I saw that, but for some reason only the first season of that show has custom titles, while the rest has only "Chapter X" titles, so that wouldn't work for the whole show.

Slightly off topic, but concerning custom episode format: is there a way to only show the season in the subtitle and remove the "•" and "Episode X" part? I have a few shows without episode titles, so the names would already be "Episode X".

**Comment by CollinHeist** [comment]
> I saw that, but for some reason only the first season of that show has custom titles, while the rest has only "Chapter X" titles, so that wouldn't work for the whole show.

Gotcha - hate when shows do that, haha.

> Slightly off topic, but concerning custom episode format: is there a way to only show the season in the subtitle and remove the "•" and "Episode X" part? I have a few shows without episode titles, so the names would already be "Episode X".

If you want to just show the season text (and you want the bold text for that), then I'd do this:

```yaml
template:
  season_text_only: 
    card_type: CollinHeist/StandardAllBoldCard
    seasons:
      hide: true
    episode_text_format: "SEASON {season_number}"
```
That hides the season text (and therefore the separator), makes the "episode text" spot effectively the season text, and then uses a [custom card type](https://github.com/CollinHeist/TitleCardMaker-CardTypes/tree/master/CollinHeist#collinheiststandardallboldcard) that uses the same bold font for the episode text (so it looks like the season text).

Let me know if you have any problems

**Comment by JakobTischler** [comment]
Perfect, thank you very much.
