### ISSUE TITLE
BUG - Losing progress when docker container is restarted/recreated.

### ISSUE THREAD

**Issue by elit3ge** [CollinHeist/TitleCardMaker#256]
### Installation

Docker - master tag

### Describe the Bug

When the docker container is recreated, Modules/.objects are not part of the persistent storage eg. /config
The whole process is started from scratch.

### Expected Behavior

Data to be stored.

### Steps to reproduce the behavior

1. Spin up the docker container.
2. Recreate container.
3. Process starts again.

### Screenshots

My work around.

![image](https://user-images.githubusercontent.com/1644699/187193146-369c12f7-177a-455d-9341-ca3f03adbe60.png)

### Debug Log

```[INFO] [22-08-29 21:11:22] Read preference file "/config/preferences.yml"
[DEBUG] [22-08-29 21:11:23] Using "" ImageMagick command prefix
[INFO] [22-08-29 21:11:23] Starting TitleCardMaker (v1.10.4)
[DEBUG] [22-08-29 21:11:23] Latest remote version is v1.10.4
[INFO] [22-08-29 21:11:23] Read preference file "/config/preferences.yml"
[DEBUG] [22-08-29 21:11:23] Using "" ImageMagick command prefix
[INFO] [22-08-29 21:11:27] Starting to sync to series YAML files..
[INFO] [22-08-29 21:11:30] Updated /config/configs/sonarr_sync.yml from Sonarr```

**Comment by CollinHeist** [comment]
I think we've spoken some on Discord, but I hadn't considered this behavior. I'll think of a solution - ideally something beside asking the user to mount `/maker/.objects/`
