### ISSUE TITLE
re-sync in plex

### ISSUE THREAD

**Issue by Adamb859** [CollinHeist/TitleCardMaker#275]
**Is your feature request related to a problem? Please describe.**
I would like for a way to re-sync titles to Plex. When I refreshed my metadata it changed them all and now I can't figure out how to have tcm select them all again In Plex.
**Describe the solution you'd like**

Im a noob at coding so there might be a way to do this.

**Describe alternatives you've considered**

**Additional context**

**Comment by CollinHeist** [comment]
If this is for one series, do `--forget-cards` with the fixer (see [here](https://github.com/CollinHeist/TitleCardMaker/wiki/Using-the-Fixer#--forget-cards---forget-loaded-cards)).

If this is for a lot of series, delete the file at `/maker/modules/.objects/loaded.json` (for Docker), or `TitleCardMaker/modules/.objects/loaded.json` if you installed with Git.

Then when you re-run TCM it will update Plex again

**Comment by Adamb859** [comment]
Thanks! Deleting the loaded.json filed did the trick, been working at it for hours with no luck lol
