### ISSUE TITLE
Add new `grayscale` un/watched style option

### ISSUE THREAD

**Issue by CollinHeist** [CollinHeist/TitleCardMaker#276]
A new `unwatched_style` / `watched_style` should be added alongside `art`, `blur`, and `unique` that makes the image B/W.

I think the best option is probably `grayscale`. The best ImageMagick command modifier for this is probably `-colorspace gray`.

**Comment by CollinHeist** [comment]
It'd technically be possible (in ImageMagick) to apply both the blur _and_ grayscale styles, as they're both just boolean toggles. For prosperity, both `grayscale` and `grayscale blur` / `blur grayscale` should be supported.

**Comment by LubricantJam** [comment]
Oh interesting! Probably an even different future enhancement but is it possible to control the hardness of the blur?

**Comment by CollinHeist** [comment]
> Oh interesting! Probably an even different future enhancement but is it possible to control the hardness of the blur?

@LubricantJam Currently that's customizable per card _type_, so if anyone _making_ a completely custom card type can change that setting, but it's otherwise fixed. Not impossible to make that adjustable in the future though
