### ISSUE TITLE
Add card directory override to `sync` setup

### ISSUE THREAD

**Issue by CollinHeist** [CollinHeist/TitleCardMaker#278]
If someone wants to put all their cards in a directory _separate_ from their media directories, it can be cumbersome (or not possible with many mounted drives on Windows) to use `volumes` to remap the directories to the card location. An override option should be available.

Perhaps something like `card_directory`, for example:

```yaml
sync:
- file: sync.yaml
  card_directory: ./cards/
```

This should set all base library paths to the given directory, and the base for any `media_directory` specifications.

**Comment by durmonator** [comment]
Hey, is there any news on this being pushed into dev or master? As I would much prefer this than storing with the media, as Sonarr deletes title cards when the episodes are upgraded

**Comment by CollinHeist** [comment]
@durmonator Hey, this can currently be done _manually_ with `volumes` and `plex_libraries`, so that's an immediate fix if you want one. I've not merged this in because I haven't had time to properly test it (particularly on Windows). Hopefully soon!

**Comment by CollinHeist** [comment]
@durmonator this should be merged into `develop` with 24b3d48e340e09a633059d09b997fa216a6aad70, feel free to test it and let me know if you see any issues

**Comment by durmonator** [comment]
Hey, I will give it a test, I was going to test the other way today, but I'm happy to give this a test for you

**Comment by durmonator** [comment]
Finally got around to testing, it isn't working as expected, the files are still ending up in my media directory, I added `card_directory: ./cards/` into preferences.yml to test and nothing goes into `<tcm directory>/cards/` I double checked my version and I am definitely on the develop branch as well, I am just doing a re-run to see if that helps, I'll attach a log file after that

**Comment by CollinHeist** [comment]
@durmonator so like all changes to your sync setup, it will only apply to _new_ shows added to the sync. If you want it to apply to old ones, you'll need to delete the file (or those shows), and re-sync. Did you do that?

If so, then yeah let's look at your logs/preferences file

**Comment by durmonator** [comment]
Ah, I'm not using the sync function currently, (it is just under options in my preferences) so I have to run this under sync?

**Comment by CollinHeist** [comment]
Yeah, this only applies to the sync and the files it creates. 

You could do it manually for any non-sync series YAML files by changing the paths in your `library` and any `media_directory` specifications.
