### ISSUE TITLE
BUG - 

### ISSUE THREAD

**Issue by patan32** [CollinHeist/TitleCardMaker#299]
### Installation

Docker - master tag

### Describe the Bug

I don't know if this is a bug. There are no images found on TMDB for series. Is there way to grab the images from plex meta? 

### Steps to reproduce the behavior

1. 
2.
...

### Screenshots

![image](https://user-images.githubusercontent.com/9191703/213986404-d0f1b059-4c30-4653-bd0e-a9ce776e0cb7.png)

### Debug Log

[maker.log](https://github.com/CollinHeist/TitleCardMaker/files/10477552/maker.log)

**Comment by CollinHeist** [comment]
I don't know what show that is, so I can't find it in your log, but this behavior is described on the wiki https://github.com/CollinHeist/TitleCardMaker/wiki/Options-Attributes#image-source-priority

**Comment by patan32** [comment]
That was right on the money sir. It's working now since i changed it to plex. I might do tmdb first and plex second after it blacklists it. Thanks again.

**Comment by CollinHeist** [comment]
No problem!
