### ISSUE TITLE
Add support for Jellyfin

### ISSUE THREAD

**Issue by patan32** [CollinHeist/TitleCardMaker#300]
Any change you can add support for Jellyfin card creation?

**Comment by CollinHeist** [comment]
It's definitely possible in the future. I consider it a similarly low-priority issue like #297, because of the disproportionate development time required for a smaller user base. But it's certainly a long-term goal

**Comment by CollinHeist** [comment]
Hey @patan32 I just added this on the `develop` branch in e269f9302457ba719cb9b9def81d3fde227efdfa - if you want to test it out let me know if there are any issues.

**Comment by patan32** [comment]
@CollinHeist Thanks for the Jellyfin support. Give me few months to try this and i'll get back to you. 

Sorry just been really busy with work lately.

**Comment by CollinHeist** [comment]
No problem - I tested it on a barebones Jellyfin server and didn't see any issues, so I think I'll add it to the next release and if any issues arise feel free to make a new issue and we can go from there! I'll close this when #315 is merged.
