### ISSUE TITLE
BUG - Error when running container with yml files needed

### ISSUE THREAD

**Issue by nath2125** [CollinHeist/TitleCardMaker#302]
### Installation

Docker - master tag

### Describe the Bug

Tried starting up the container with .yml files needed and printing this error. Using unraid docker to host this container.

### Expected Behavior

_I assume work or start container_

### Steps to reproduce the behavior

1. 
2.
...

### Screenshots

![image](https://user-images.githubusercontent.com/99367069/215777084-a0f6e14c-a85e-4c2e-8445-3f85d45157b8.png)
![image](https://user-images.githubusercontent.com/99367069/215777142-0f3d7952-4c1a-4144-a47e-1eb2e7ef1ba7.png)
![image](https://user-images.githubusercontent.com/99367069/215777202-c53efc07-13be-47ed-982e-42b8bbc69f87.png)

### Debug Log

Traceback (most recent call last):
  File "/maker/main.py", line 156, in <module>
    if not (pp := PreferenceParser(args.preferences, is_docker)).valid:
  File "/maker/modules/PreferenceParser.py", line 78, in __init__
    self.database_directory.mkdir(parents=True, exist_ok=True)
  File "/usr/local/lib/python3.9/pathlib.py", line 1323, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/config/.objects'
Traceback (most recent call last):
  File "/maker/main.py", line 156, in <module>
    if not (pp := PreferenceParser(args.preferences, is_docker)).valid:
  File "/maker/modules/PreferenceParser.py", line 78, in __init__
    self.database_directory.mkdir(parents=True, exist_ok=True)
  File "/usr/local/lib/python3.9/pathlib.py", line 1323, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/config/.objects'
usermod: no changes
[INFO] Read preference file "/config/preferences.yml"
usermod: no changes
[INFO] Read preference file "/config/preferences.ym

**Comment by CollinHeist** [comment]
@nath2125 does the `/mnt/user/appdata/TitleCardMaker/` directory exist? If so, does the 314:314 group have R/W permissions for that folder? 

I might change your `/config` directory to `/mnt/user/appdata/TitleCardMaker/config/` and create that folder ahead of time and see if that fixes the problem.

**Comment by nath2125** [comment]
/mnt/user/appdata/TitleCardMaker/ this is the main directory for all the configuration files yes and has been created with the yml files in there. Should i be changing it to /mnt/user/appdata/TitleCardMaker/config/ instead? Not sure about the permissions part as i didnt set any and it would be what ever comes default for unraid docker containers, probably root:root.

**Comment by CollinHeist** [comment]
> /mnt/user/appdata/TitleCardMaker/ this is the main directory for all the configuration files yes and has been created with the yml files in there. Should i be changing it to /mnt/user/appdata/TitleCardMaker/config/ instead? [...] This container was also in the community app store preconfigured so i didnt create this fields myself although they dont woke so some changes will need to be made

Well that's odd, the template of the container for the Unraid app store has the `/config` mount path defaulting to `/mnt/user/appdata/TitleCardMaker/config/`, I don't know why it would be ignoring _just_ the `/config` part of that. But what you have should work fine.

![Screen Shot 2023-02-01 at 9 38 51 AM](https://user-images.githubusercontent.com/17693271/216105665-a2903870-9f44-4707-a89e-4a9fcff20b23.jpg)

> The "missing file" and "global preference file" are suppose to refer to the /config mount that gets created with the /mnt/user/appdata/TitleCardMaker/ as the host mount which then turns into the /config inside the container and then ties back to the missing file and global preference fields where they are /config/xxx

Yes that's correct, these are not the problem.

---

So most likely the parent directory `/mnt/user/appdata/TitleCardMaker` or `/mnt/user/appdata/TitleCardMaker/.objects` does not have the correct permissions, you should try chown-ing or chmod-ing those directories, you could also just delete `/mnt/user/appdata/TitleCardMaker/.objects` if it exists.

**Comment by CollinHeist** [comment]
I'm going to close this issue, let me know if you're still having issues / questions

**Comment by nath2125** [comment]
I've managed to bring it down to this. I fixed some of the other messages I was getting. I also changed the unraid docker container permissions to PGID: 100, PUID:99 since some of my other containers use that level for permissions but still same result. I apologise, I'm not that familiar with permissions. 

`Traceback (most recent call last):
  File "/maker/main.py", line 156, in <module>
    if not (pp := PreferenceParser(args.preferences, is_docker)).valid:
  File "/maker/modules/PreferenceParser.py", line 82, in __init__
    self.database_directory.mkdir(parents=True, exist_ok=True)
  File "/usr/local/lib/python3.9/pathlib.py", line 1323, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/config/.objects'
[INFO] Read preference file "/config/preferences.yml"
usermod: no changes
[INFO] Read preference file "/config/preferences.yml"`

Is there anyone who's created a guide for unraid setup? Or only the docker one I see?

**Comment by CollinHeist** [comment]
@nath2125 Did you do this?

> So most likely the parent directory /mnt/user/appdata/TitleCardMaker or /mnt/user/appdata/TitleCardMaker/.objects does not have the correct permissions, you should try chown-ing or chmod-ing those directories, you could also just delete /mnt/user/appdata/TitleCardMaker/.objects if it exists.

The error you are getting still means however you are running TCM it does not have the permission required to create the directory at /config/.objects (wherever you mounted that)

And assuming you have the permissions set up correctly the guide for Unraid is identical (slightly easier/difference since you don't have to type the Docker commands) than the Docker one

**Comment by nath2125** [comment]
I didnt see a field where it would mount .objects in the container configuration? 

These are the permissions I'm seeing for the container
![image](https://user-images.githubusercontent.com/99367069/224452949-69126b2a-019b-4e55-9849-d4245c8f69e0.png)

![image](https://user-images.githubusercontent.com/99367069/224452974-d3585b3b-3113-4a42-85b7-5432963844a2.png)

**Comment by CollinHeist** [comment]
You won't need/want to mount the .objects directory, that's created by TCM alongside your preferences file.

I think we should try and give 314:314 ownership of the TitleCardMaker directory, instead of root. Try `chown -R 314:314 /mnt/user/appdata/TitleCardMaker`

**Comment by CollinHeist** [comment]
So there is some other permission error going on. Quadruple check that the UID and GID you are providing have RW+ access to that folder and all subfolders, do chmod 777 if you need to. Sadly I am not going to be much help since I do not know your permission structure

**Comment by nath2125** [comment]
Yea sadly I don't know permissions either so I'm at the mercy of anyone who does. 
For my container, I have these permissions.
![image](https://user-images.githubusercontent.com/99367069/224600941-5d86f2ca-06d3-47d6-83fe-ceb388ef1655.png)
Not sure if that may shed light on the issue?
And then a screenshot of the change I made before, just to check I did it correctly.
![image](https://user-images.githubusercontent.com/99367069/224601080-b9a0ebf0-d9f5-4a08-ade5-159b19ad51c9.png)

**Comment by CollinHeist** [comment]
It looks like you had been using 314:314 (the container defaults). If you have changed this to 100:99, then you'll want to modify the permissions of the TitleCardMaker folder to match that. Whatever GID+UID you use needs to match in the folder and container.

**Comment by nath2125** [comment]
I just changed it and it removed the error, I believe. Thanks for your help and patients
