### ISSUE TITLE
Setup Questions

### ISSUE THREAD

**Issue by JohnDoranNY** [CollinHeist/TitleCardMaker#324]
In my Series yml I have the following:

episode_text_format: Season {season_number} • Episode {episode_number}

And what seems to happen is it created the title card (I am using Fade with a logo) I get "SEASON 1 • SEASON 1 • EPISODE 1" (ep 2, ep 3, etc).

**Comment by CollinHeist** [comment]
@JohnDoranNY Is there a reason you are putting the season number inside your episode text?

The `episode_text_format` option is the format of _episode_ text. Season text is controlled with [seasons](https://github.com/CollinHeist/TitleCardMaker/wiki/Season-Specification).

The default season and episode text for that card is `SEASON {season_number} • EPISODE {episode_number}` so you can not specify anything at all if that's the format you want

**Comment by JohnDoranNY** [comment]
I guess cuz I'm an idiot? lol. I just installed this a few hours ago and having a hard time to configure for windows. :(  I will check out the tags better.

**Comment by CollinHeist** [comment]
Haha that's fine, the options aren't very clear. Just remove that option altogether, that will remove the repeat text.

Did you need help getting it set up on Windows?

**Comment by CollinHeist** [comment]
You _should_ be able to make 3.11 work if you update `Pipfile` to say 3.11 instead of 3.9, like so (haven't tested this):
```ini
[requires]
python_version = "3.11"
```

Beyond that, network drives are tricky because of how Windows displays them. Specify the drive like `N:\\your\drive`, or if it has a server name (like `\\serverName\`) you can try that. But TCM will work better if the cards are local, and it can load the cards into Plex directly, they do not need to be next to your media.

**Comment by JohnDoranNY** [comment]
One thing that might be really helpful is to include a set of sample files (with comments) in the distribution.  Not essential but I think it might have made some of this easier to get up and running.

**Comment by CollinHeist** [comment]
Did you remove the old environment (`pipenv --rm`), and then update the Pipfile to require 3.11 and reinstall?

>  am curious how it will work on multi-directory libraries (like tv shows = d:\path 1, d:\path 2, d:\path 3)

If you are syncing from Plex it will handle that without issue, if you are syncing from Sonarr it requires a bit more setup to get the library paths right.

**Comment by JohnDoranNY** [comment]
**Did you remove the old environment (pipenv --rm), and then update the Pipfile to require 3.11 and reinstall?**

No I did not. I must admit, while I am a developer, it is in .NET and C#. I know next to nothing about python (but slowly starting to learn)

**Comment by CollinHeist** [comment]
That's fine, there's no reason you'd know to do that. But if you wanted to make 3.11 work that might do the trick

**Comment by JohnDoranNY** [comment]
I do see it now. Thanks

I am having another issue. I edited my tv.yml, commented out 3rd rock from the sun, added succession, put in the tvdb_id and tmdb_id, but when I run it looks like its still trying to process 3rd rock from the sun. I checked carefully preferences and tv yml's line by line to make sure no errors but.. it creates (under sources) a folder called Succession (2018) and fills it with 3rd rock episode images.  (BTW: it keeps breaking when I use TMDB as the image source for 3rd rock. it gets 2 pictures then exits script).

**Comment by CollinHeist** [comment]
I'd have to see your YAML files and the log to pinpoint the issue, if you want to edit out your API keys and post those here. The log file is at `logs/maker.log`

**Comment by JohnDoranNY** [comment]
I think I fixed it.  It's happened on a couple of shows actually.  I think if there was an issue during processing, there is something still 'cached' causing the issue.  I went into modules\objects and looked through the json files. I removed the offending series, and renumbered any that came after (to keep the increment proper) and that solved the issue. Next run it pulled the right series from Plex (and images) instead of the prior series (and images) that was run prior.  This has happened to me 3 times and all 3 times the only way to solve it was to do the above.

This brings me to another issue though.  If I read right, in the Series yml, I have the following:

  Antique Bakery:
    name: Antique Bakery
    episode_data_source: plex
    library: TV Shows
    card_type: fade
    year: 2008
    watched_style: unique
    unwatched_style: unique
    filename_format: '{name}.S{season:02}E{episode:02}.{title}'
    **image_source_priority: tmdb, plex**
    extras:
      logo: C:\[2D] Television\Antique Bakery (2008)\clearlogo.png
      separator: •
    tvdb_id: 83013
    tmdb_id: 34741

My understanding (from the wiki) was that for image_source_priority, it would try the first entry (above = tmdb) and if it timed out 5 times it was blacklisted, and would fall back to the next entry.  However, this never seems to fall back.  Everytime there are no images for a series/episode on TMDB it will fail and move to next series. I have to rerun with only plex and then it works.

**Comment by CollinHeist** [comment]
Most likely you had listed the wrong database ID's for the series, so TCM was matching to those wrong ID's - deleting those files would also fix the issue, but glad it's working now!

---

A few things, I _assume_ your YAML actually looks like this:
```yaml
Antique Bakery:
  name: Antique Bakery
  episode_data_source: plex
  library: TV Shows
  card_type: fade
  year: 2008
  watched_style: unique
  unwatched_style: unique
  filename_format: '{name}.S{season:02}E{episode:02}.{title}'
  image_source_priority: tmdb, plex
  extras:
    logo: C:\[2D] Television\Antique Bakery (2008)\clearlogo.png
    separator: •
  tvdb_id: 83013
  tmdb_id: 34741
```
a couple of comments about this:
1. If your name is already `Antique Bakery`, you don't need to re-define the `name: Antique Bakery`, you can remove that.
2. If your global episode data source is already Plex, you can remove that from the series (unless you want to overwrite it). Same with `watched_style` and `unwatched_style`, as well as `filename_format`, and `image_source_priority`.
3. Specifying the year as `year: 2008` is fine, but it might save you some typing to just list the parent name as `Antique Baker (2008)`
4. The default `separator` for the `FadeTitleCard` is `•`. You can omit this unless you want to change it to something else.
5. TCM finds series automatically, it is rarely required to specify any database ID's manually. So _most likely_ you can remove `tvdb_id` and `tmdb_id`.

---

All in all, I suspect your series YAML can look like this:
```yaml
Antique Bakery (2008):
  library: TV Shows
  card_type: fade
  extras:
    logo: C:\[2D] Television\Antique Bakery (2008)\clearlogo.png
```
Which is much simpler for you to maintain. Also, you might look into setting up the [sync](https://github.com/CollinHeist/TitleCardMaker/wiki/YAML-Sync), as TCM will write these YAML files for you and save you all the manual work.

---

As for your image source priority question, TCM only counts retries separated by an interval of time, here's blurbs from the Wiki:

> If tmdb is a higher priority than Emby/Jellyfin/Plex, then Emby/Jellyfin/Plex will only be queried for source images after that episode has been "permanently blacklisted" by TMDb - i.e. has failed more than the specified [retry count](https://github.com/CollinHeist/TitleCardMaker/wiki/TMDb-Attributes#retry-count).

> In order to limit unnecessary API queries to TMDb caused by repeatedly asking for a resource that does not exist, a specific episode is "blacklisted" after this specified number of operations. All failed operations are temporarily blacklisted for 12 hours before being tried again; however, if the same operation has failed retry_count many times, it is permanently skipped.

So most likely you just need to wait for those intervals to pass. Or you can lower your retry count.

**Comment by JohnDoranNY** [comment]
I will read the above in a moment. I tracked down the file that is a problem with scraping the wrong series.. It has happened now a 4th time, with errors leading up to it.   This time I was scraping Arrow (2012) and Atam Man vs. Superman (1950).  I have the proper tvdb_id and tmdb_id in the series.yml for each (triple checked now before posting this).

In series_infos.json:

    "42": {
      "full_name": "Arrow (2012)",
      "emby_id": null,
      "imdb_id": "tt2193021",
      "jellyfin_id": null,
      "sonarr_id": null,
      "tmdb_id": 1412,
      "tvdb_id": 257655,
      "tvrage_id": 30715
    },
    "43": {
      "full_name": "Ash vs Evil Dead (2015)",
      "emby_id": null,
      "imdb_id": "tt4189022",
      "jellyfin_id": null,
      "sonarr_id": null,
      "tmdb_id": 62264,
      "tvdb_id": 296295,
      "tvrage_id": 46180
    },
    "44": {
      "full_name": "Atom Man vs. Superman (1950)",
      "emby_id": null,
      "imdb_id": "tt2193021",
      "jellyfin_id": null,
      "sonarr_id": null,
      "tmdb_id": 1412,
      "tvdb_id": 257655,
      "tvrage_id": 30715
    }
Please notice the infor for 42 (Arrow) and 44 (Atam Man vs Superman).  Other than full name, all the other data is the same. imdb_id, tmdb_id, tvdm_id, tvrage_id.  I have no idea why it does this.  It was was only 3 series scraped (Ash vs Evil Dead (2015) was the 2nd - 43).  No errors for either arrow or ash vs evil dead but it still repeated Arrow data as Atom Man data.

**Comment by JohnDoranNY** [comment]
Just for clarity: the series.yml

  Arrow:
    library: TV Shows
    card_type: fade
    year: 2012
    extras:
      logo: C:\[2D] Television\Arrow (2012)\clearlogo.png
    tvdb_id: 257655
    tmdb_id: 1412


and

  Atom Man vs. Superman:
    library: TV Shows
    card_type: fade
    year: 1950
    extras:
      logo: C:\[2D] Television\Atom Man vs. Superman (1950)\clearlogo.png
    tvdb_id: 168321
    tmdb_id: 106358

I specifically added tmdb_id and tvdb_id in hopes of avoiding confusion during scraping but ...

**Comment by JohnDoranNY** [comment]
Read your comments above and simplifying my config.  I though the year was only allowed in the header if it was listed that way in plex (a few are, most are not)... so I was adding the year when it was not part of the title name in plex.

Also I would love to use Sync but since I am using the fade template and it requires a transparent logo, I have been doing it manually.  Not sure how to automate where it should look for the logo file.

**Comment by CollinHeist** [comment]
If you delete that JSON file and then delete all the ID's from your series YAML file, does it still incorrectly match those series?

---

The year is allowed in the header in all circumstances, even if it's not present in the name within Plex.

---

You can auto-assign a logo when syncing, I'd recommend using a template. For example:

```yaml
# preferences file
plex:
  # options
  sync:
  - file: ./plex_sync.yml
    add_template: logo_template

# plex_sync.yml
templates:
  logo_template:
    card_type: fade
    extras:
      logo: logo.png
```

Then TCM will sync series like this:
```yaml
series:
  Arrow (2012):
    # library / directory here
    template: logo_template
```

**Comment by JohnDoranNY** [comment]
OMG I am soooooooooo happy I don't need to keep looking up the tmdb_id and tvdb_id for each series.. this has been a slow process so far :D I am testing with Attack on Titan (2013) and it works great so far without the id's specified.

I will try the template option.  What happens though if there is no clearlogo.png in the series home directory on plex? does it just fail?  Also, I have been going crazy trying to find this information in the wiki but how do I configure this to create title cards for specials (using plex's images since they may not exist on tmdb).  I have a lot of series i've scraped so far that have specials (season 0) and they are always ignored. I even tried to edit the dat file to add the specials episode manually (season 0: 1: special name) and that only caused an error that crashes the application.

**Comment by JohnDoranNY** [comment]
FYI: I am thinking to submit a new card style for you (I will create the png file and a new py file for it).

I create poster art on ThePosterDB.com  (https://theposterdb.com/user/JohnDoranNY)  I am thinking to create a template similar to Fade but using the format closer to what I create for series cover and seasons posters.  If you check the link above you will get my meaning.  The fade works nicely but not perfectly with the theme... I will be more than happy to zip up the final product and send to you, if you are interested in providing it with your distribution.

**Comment by CollinHeist** [comment]
> OMG I am soooooooooo happy I don't need to keep looking up the tmdb_id and tvdb_id for each series.. this has been a slow process so far :D I am testing with Attack on Titan (2013) and it works great so far without the id's specified.

Yes that would be very tedious, lol. Glad it's working.

> What happens though if there is no clearlogo.png in the series home directory on plex?

So TCM will automatically try to download a logo for all series from TMDb. If it's not present, a few things (1) it will appear in your missing file so you can go and grab one if you want; and (2) it will just not create the cards since you've specified a logo that doesn't exist. For series without logos you can just not specify a logo (or grab one from somewhere).

> I have been going crazy trying to find this information in the wiki but how do I configure this to create title cards for specials (using plex's images since they may not exist on tmdb). I have a lot of series i've scraped so far that have specials (season 0) and they are always ignored. I even tried to edit the dat file to add the specials episode manually (season 0: 1: special name) and that only caused an error that crashes the application.

There is a global setting `sync_specials` that you need to make sure is `true` - see [here](https://github.com/CollinHeist/TitleCardMaker/wiki/Options-Attributes#special-syncing). This is adjustable per-series as well. Most likely you just had some bad YAML formatting, that is very particular or else it'll cause a crash. But if this setting is true, and your episode data source is Plex and you have the special in Plex it will grab episode data for those episodes. You might need to wait for TCM to get images from TMDb and then Plex.

---

> FYI: I am thinking to submit a new card style for you (I will create the png file and a new py file for it).

Yeah I'd love that! I always like having more options for users. There is actually a companion repository set up for hosting user-created card types so anyone can use them - see [here](https://github.com/CollinHeist/TitleCardMaker-CardTypes). I can help you get your card submitted there if you need

**Comment by JohnDoranNY** [comment]
> You can auto-assign a logo when syncing, I'd recommend using a template. For example:

I tried your sample but it fails because its looking in the TCM base directory. I am not sure how to use this template to say 'look at the directory the plex media files are'.

**Comment by CollinHeist** [comment]
Sorry, that was a typo on my part, I meant this:
```yaml
templates:
  logo_template:
    card_type: fade
    extras:
      logo: ./source/<<clean_title>> (<<year>>)/logo.png
```
That will use the logos from the series' source directory.

**Comment by CollinHeist** [comment]
I am going to close this issue for now, please re-open or start a new one if you have any other questions/issues!
