### ISSUE TITLE
logo.png not downloading

### ISSUE THREAD

**Issue by Palle34** [CollinHeist/TitleCardMaker#329]
Hey there,
I have a problem. I want to create title cards for some German TV shows, but he logo.png file is not downloaded/created, although it is displayed on the TMDB website.
I think this is because the logo has a language tag applied to it.
Is there an option to ignore the language tag? Something like skip_localized_images but for logos?

**Comment by CollinHeist** [comment]
Currently TCM only looks for and grabs English logos. I might consider adding an option to specify which languages of logos to search for, but that's not currently possible

**Comment by Palle34** [comment]
It would be great if you could add that :D

**Comment by CollinHeist** [comment]
@Palle34 I created #330, and should be able to implement this in the next version, but I'll also tag these issues with `in-develop` when it's on the develop branch/tag.

**Comment by CollinHeist** [comment]
@Palle34 Alright I've added this to the develop bracnh/tag. So if you pull from git/Docker, you should be able to prioritize German and English logos by adding this to your TMDb preferences:
```yaml
tmdb:
  # other options
  logo_language_priority: de, en # German then English
```
Let me know if you have any issues

**Comment by Palle34** [comment]
Works great. Thanks :D

**Comment by CollinHeist** [comment]
No problem!
