### ISSUE TITLE
Create `TintedFrameTitleCard` new card type

### ISSUE THREAD

**Issue by CollinHeist** [CollinHeist/TitleCardMaker#331]
I don't have a name for this one (maybe blur border or something like that), but I had another idea for a title card that looks like this:

<img src="https://user-images.githubusercontent.com/17693271/233257029-8b17ce2e-01ea-4ae3-bc73-54e152be4d31.jpg">

The central idea being a rectangular frame with blurred content _outside_ the rectangle, and the title and index text intersecting the rectangle.

---

Additionally, in place of the index (season + episode) text at the bottom, a logo _should_ be place-able; the box and episode text color should also be adjustable - all via extras. For example:

<img src="https://user-images.githubusercontent.com/17693271/233257805-7054f0f0-3db5-4deb-a580-51d76ef5d095.jpg">

---

The ImageMagick commands for this shouldn't be too outrageous; I think blurring the entire image and overlaying an unblurred clone for the middle section is easy enough; and then the most difficult/tedious part will be calculating the line/rectangle dimensions to not overlap the text or logo.

**Comment by CollinHeist** [comment]
A suggested name from the Discord is Tinted Frame (so `TintedFrameTitleCard`, because of the similarity to the tinted glass card.

`card_type` identifiers should be:
- `tinted frame`
- `blurred border`

**Comment by AsafOti** [comment]
Thank you for your work, you made my Plex Library looks beautiful

I have tried to but tinted frame blurred border into the card_type: section but unfortunately in the logs it show as:

- [ERROR] Invalid card type "tinted frame"
- [ERROR] Invalid card type "blurred border"

or 

- [ERROR] Cannot identify remote Card Type "tinted frame"
- [ERROR] Cannot identify remote Card Type "blurred border"

**Comment by CollinHeist** [comment]
@AsafOti Hey! Glad you're enjoying the project.

I just created this card type, and so it hasn't been "released" outside of the `develop` branch/tag yet. It will be in the `v1.14.0` release, which I'll probably release later today.

If you switch to that branch/tag, you should be able to use this card without waiting
