### ISSUE TITLE
Ability to use PMS Tag (label) as a filter per-episode 

### ISSUE THREAD

**Issue by JohnDoranNY** [CollinHeist/TitleCardMaker#338]
Hello Collin.

I've been using local custom cards to generate new title cards.  

One thing I wish I could be able to do is to read the value of a Plex episodes 'Label" property to see if a text string exists and use a custom frame based on if that label exists or not.  While it seems silly it can actually be pretty helpful. For example: lets say I go through my series and mark each 'Xmas' episode by assigning it the 'Christmas" label.  If I were able to check this per episode during card creation, I could say "hey!  this is an Xmas episode, let's use that fancy Xmas Title Card we created for just this situation!"

I'm doing this, kinda, the Data.yml for a specific series that contain episodes that would use different frame types.  This would be a pain in the... well... to continue this moving forward.  It would be much simpler to be able to mark it in the plex interface and let TCM find it and handle card creation automatically based on this.. so I can create a custom card with 5 different variations of the same overlay, and programmatically look for xmas, special, live, etc, and use the associated overlay, else, default to the standard overlay.  

I remember there was a filter for plex to pull only series that matched a plex tag... but i do not know if plex, itself, can return the label property when you pull the name, episode, etc.  BTW: to be clear, I am talking about tags on the episode level, not series or season level. Thanks!

**Comment by JohnDoranNY** [comment]
I mean the overlay itself.  I've attached some images to show what i mean.

![RiffTrax (2006)](https://github.com/CollinHeist/TitleCardMaker/assets/32340247/1cd2c618-b140-484b-a10b-2593e1095233)

This is the custom Series cover 

![RiffTrax (2006) - Specials](https://github.com/CollinHeist/TitleCardMaker/assets/32340247/4fefbbe5-7cb6-4fca-b51c-011fc0c2331d)

This is the custom Season (Specials)

![RiffTrax S00E79 Just Awful (Kickstarter Reward)](https://github.com/CollinHeist/TitleCardMaker/assets/32340247/f9cba63d-d155-4c0d-8148-08fa62d6f2ab)

Here is a sample of a 'standard' matching title card

![RiffTrax S00E81 The RiffTrax Yule Log](https://github.com/CollinHeist/TitleCardMaker/assets/32340247/f3309644-d92e-49c6-b5dd-6ac311e8a6bb)

Here is a Xmas episode with custom frame meaning instead of simply silver wired frame around the outside of the card, it has a red/green tinted frame.

![RiffTrax S00E106 How to Be Courteous to Mary Jo (Kickstarter Reward)](https://github.com/CollinHeist/TitleCardMaker/assets/32340247/e2300329-8df4-4e39-bb81-4d099706c7df)

And here is a sample of 'other' hosts/riffers.   When the episode features Bridgett Nelson and Mary Jo Perl, I use a purple boarder. When its 'other' hosts  I use a blue frame.

**Comment by CollinHeist** [comment]
@JohnDoranNY Overlays are a part of PMM, not TCM. TCM is used to create those title cards (underneath your frame overlay), but has nothing to do with the overlay styling or generation. This suggestion probably belongs on the PMM GitHub

**Comment by JohnDoranNY** [comment]
The above post was based predominantly on two existing templates, Fade and Beedman, modified to be the above.  Currently in the series Data.yml file, I have a 'frame' attribute with  Christmas, Purple, Blue, LGBTQ, etc, for any episode that is not 'standard' so it pulls that overlay to use.

**Comment by CollinHeist** [comment]
Are those frame overlays being generated by a custom card type you've created?

**Comment by JohnDoranNY** [comment]
Yes they are custom TCM card called (originally enough) RiffTraxCardType.py.  Like the Fade uses 'logo', and Anime uses 'kanji' attributes, I added a 'frame' attribute to the data.yml and to the series.yml.  So the one card type will choose from a total of 6 different gradient.png files based on the value of 'frame'.

**Comment by JohnDoranNY** [comment]
These are the Card gradients

![standard](https://github.com/CollinHeist/TitleCardMaker/assets/32340247/c1c41002-169b-490e-ad51-89d2ea515778)
Standard

![christmas](https://github.com/CollinHeist/TitleCardMaker/assets/32340247/05b35c2f-2348-465c-92ba-9b6b6ba49a2a)

Chistmas

![horror](https://github.com/CollinHeist/TitleCardMaker/assets/32340247/1e2d6ad5-ec41-44c3-a30b-bee8fb2b1297)

Horror

![lgbtq+](https://github.com/CollinHeist/TitleCardMaker/assets/32340247/381244fc-ed7a-4e16-a996-33ca6ffabb4d)

LGBTQ+

(and a couple of others)

**Comment by CollinHeist** [comment]
I understand, sorry for the confusion when you said "overlay" I assumed you meant a PMM overlay. I think I'm on the same page now.

Would it be sufficient to pass in any per-episode tags to the card's `__init__` method? Then you can determine how to apply those, perhaps via an extras mapping that you can specify? Or did you have something else in mind.

---

P.S. Love the card, very creative, you should consider submitting it to the [companion repository](https://github.com/CollinHeist/TitleCardMaker-CardTypes) if you'd like to share it.

**Comment by JohnDoranNY** [comment]
Sorry it doesn't display the gradient transparent png images

**Comment by JohnDoranNY** [comment]
> I understand, sorry for the confusion when you said "overlay" I assumed you meant a PMM overlay. I think I'm on the same page now.
> 
> Would it be sufficient to pass in any per-episode tags to the card's `__init__` method? Then you can determine how to apply those, perhaps via an extras mapping that you can specify? Or did you have something else in mind.
> 
> P.S. Love the card, very creative, you should consider submitting it to the [companion repository](https://github.com/CollinHeist/TitleCardMaker-CardTypes) if you'd like to share it.

Thanks! I have every intention of submitting, once I get it all down right.  For some shows like "Evil" or "Walking Dead" I use a 'Horror" frame meaning instead of it being silver, it is in dark red. I am working now on using a different font color and style for those marked as "Horror"...  I have a few more days I think of tweaking then will gladly submit.

My original question was, are you able to pull the 'label' dictionary per episode from plex when you scrape the episodes, and in the card file we can ask "is 'Xmas' in lstPlexLabels:  so instead of it being configured manually in every series Data.yml file, we can set it once in Plex, per episode, what special attribute for that episode so we can choose which matching card type to use.

**Comment by JohnDoranNY** [comment]
FYI: it works now using the data.yml per episode or series.yml per show.  It is tedious though. I have 987 episodes for Riffrax so far (and it grows weekly).  To modify the YML's for each new episode is not optimum. Workable but not optimum.  IF we could assign a tag in Plex per episode, and use that as a filter when deciding which gradient to use for a card set. I guess this would be the first official 'card set' where its one card with 6 subtly different (but matching) gradient overlays.  It may not be a feature many would use. I just find it useful in my situation. I like to be able to show xmas episodes for any series with an xmas'y frame so its easy to see on first glance which are the holiday episodes. I do the same with my movie posters using the same format as above.

**Comment by CollinHeist** [comment]
> I have every intention of submitting, once I get it all down right. For some shows like "Evil" or "Walking Dead" I use a 'Horror" frame meaning instead of it being silver, it is in dark red. I am working now on using a different font color and style for those marked as "Horror"... I have a few more days I think of tweaking then will gladly submit.

Perfect. Let me know if you want any help.

> My original question was, are you able to pull the 'label' dictionary per episode from plex when you scrape the episodes, and in the card file we can ask [...]

Yes I think that should be doable. I will probably provide the data as
```python
episode_tags: list[str] = []
```
So you can then just look for a specific tag in that list within your card file, and adjust the styling accordingly.

**Comment by JohnDoranNY** [comment]
btw: in case you were interestsed, this is how it fits in once done for a season:

![Screenshot 2023-05-17 205121](https://github.com/CollinHeist/TitleCardMaker/assets/32340247/c02c8ae9-cd9c-42f7-b60a-43f7bd7e3407)

Episodes with Mary Jo and Bridget have a purple frame, Christmas movies have the green/red stripes, otherwise, silver frame. It makes it so much easier (visually) to pick episodes to watch.

**Comment by JohnDoranNY** [comment]
> > I have every intention of submitting, once I get it all down right. For some shows like "Evil" or "Walking Dead" I use a 'Horror" frame meaning instead of it being silver, it is in dark red. I am working now on using a different font color and style for those marked as "Horror"... I have a few more days I think of tweaking then will gladly submit.
> 
> Perfect. Let me know if you want any help.
> 
> > My original question was, are you able to pull the 'label' dictionary per episode from plex when you scrape the episodes, and in the card file we can ask [...]
> 
> Yes I think that should be doable. I will probably provide the data as
> 
> ```python
> episode_tags: list[str] = []
> ```
> 
> So you can then just look for a specific tag in that list within your card file, and adjust the styling accordingly.

That would be PERFECT! and would open up so much flexibility in card designs.

**Comment by CollinHeist** [comment]
Question for you, how are you adding the labels per-Episode within the Plex UI? I haven't seen how to do that before

**Comment by JohnDoranNY** [comment]
I guess I'm not.  A few years back I added tags to episodes. It looks like in those years that feature no longer exists (?).  I'm *almost* positive we used to be able to assign labels on the episode level.  I will research this a bit more but it looks like perhaps my request is not possible. It looks like the only way possible is to hack one of the director or writer fields and add 'christmas' or whatever there but I hate doing sloppy hacks.  Maybe 'genre' would be a better match. Christmas is kinda a genre anyway. But even that is not available on the episode level (not sure if it ever was).    Ugh.  I guess this means having to maintain the data.yml files per series then.  I don't see any elegant solution.

**Comment by JohnDoranNY** [comment]
As a test I will see what happens when I add episodes to a collection.  Perhaps that might be a way to tag it.

**Comment by CollinHeist** [comment]
Oddly enough Episodes _can_ have tags/labels added to them, just not from the Plex interface. It is possible via the API, though.

**Comment by JohnDoranNY** [comment]
Strange.  My thoughts on this is: collections will not work.  Collections are not assigned to an episode.. an episode is assigned to a collection.  To do this you would need to query all collections for tv episodes which would be a nightmare and impractical.  You used to be able to assign labels (sharing) via the web interface but I guess no longer...  I wonder what 3rd party tools are out there.  Honestly though, I guess this is too big an issue to deal with.  Unless there was an easy way to update the data in plex to assign the label to the episode, it would be way too much work to get the data in there for normal users.  I wonder if PMS has any capability there. I should check that out.

**Comment by CollinHeist** [comment]
Yeah it's unfortunate that the ability to tag them within the interface has been removed, I wonder why they did that.

I will probably still add the per-Episode tags as an available option to cards, in case some other users think of uses for them. But for TCM, when the web interface is released you will be able to easily add per-Episode data/extras like would be necessary here (without digging in data files). So perhaps keep an eye open for that. It will be made available to sponsors soon, and eventually a wider release.

**Comment by CollinHeist** [comment]
@JohnDoranNY So I think I'll close this issue, for now. I think it's a very good suggestion, just not likely to be used since the tags cannot be added from the UI. As I mentioned above, in TCM v2.0 (the web UI), you will be able to very easily add per-Episode data / overrides - so it can always be accomplished with that.

I still recommend you submit your card type for others, let me know if you have any other issues!
