### ISSUE TITLE
HELP -  Some Questions

### ISSUE THREAD

**Issue by VampiricAlien** [CollinHeist/TitleCardMaker#401]
### Installation

Docker - develop tag

### Describe your Problem

1. If a tv show has a date in it but others do not, how does TCM deal with that? (filename_format: "{name} S{season:02}E{episode:02} {title}") but many could be 'title S01E01.mp4 or the folder might be (2023) and jellyfin has it as show title with no year'

2. When you're finished with beta, is there going to be a setup wizard or place to download dummy files?

3. When naming the episodes, if Jellyfin and sonarr have different names, how does TCM work with this ( Sonarr could be   S01E01 but jellyfin matched it to episode title S01E01)

4. Is it possible to rotate the logs on each restart?
 

### Preference File

```yaml
N/A
```

### Debug Log

N/A

**Comment by CollinHeist** [comment]
@VampiricAlien Sorry for the delay, I must have missed this.

1. The actual file naming of your video files does not matter, TCM just loads the Cards via the API. The adjustable filename format is just for customization (if you want it)
2. I did not have plans to have any sort of setup wizard or dummy files, I don't see a need. There are updated docs [here](https://titlecardmaker.readthedocs.io/en/latest/). Did you have something in mind? 
3. TCM grabs the titles from your assigned episode data source; and when matching to Jellyfin it looks for matches by episode database ID (TVDb/TMDb/IMDb/etc.), then by index + title.
4. Not currently. Logs are rotated every day
