### ISSUE TITLE
BUG - Documentation Typo

### ISSUE THREAD

**Issue by Droppisalt** [CollinHeist/TitleCardMaker#414]
### Installation

Docker - master tag

### Describe the Bug

Typo can be found here:
https://github.com/CollinHeist/TitleCardMaker/wiki/YAML-Sync#sonarr
https://github.com/CollinHeist/TitleCardMaker/wiki/YAML-Sync#sonarr-1

`series_type: tv` should be `standard`

### Steps to reproduce the behavior

1. 
2.
...

### Debug Log

```
[INFO] Read preference file "/config/preferences.yml"
[ERROR] Cannot filter by series_type "tv" - must be one of anime, daily, standard
```

**Comment by CollinHeist** [comment]
@Droppisalt Thanks so much! Nice catch. I believe I've fixed that, but let me know if I missed one.

**Comment by Droppisalt** [comment]
For sure. Going through the documentation to help a friend. If I see others, I'll let you know

**Comment by CollinHeist** [comment]
Sounds good! Well ping me if you see anything that's wrong (or even confusing)

**Comment by Droppisalt** [comment]
@CollinHeist this image is missing: https://github.com/CollinHeist/TitleCardMaker/wiki/OverlineTitleCard#spoiler

And thank you for offering help! I'll send a question on discord later tonight.

**Comment by CollinHeist** [comment]
Oh weird, it must be cached in my browser or something, it is loading for me. I'll fix that now, thanks
