### ISSUE TITLE
BUG - 

### ISSUE THREAD

**Issue by TechJedi51** [CollinHeist/TitleCardMaker#419]
### Installation

Docker - master tag

### Describe the Bug

Question marks being changed to exclamation marks in folder and file names

### Expected Behavior

In macOS (and I think in Windows) Question marks are acceptable for file/folder names. Is it possible to change this behavior? When Sonarr create a folder it has the question mark for the name and TCM is creating a new folder with the exclamation mark.

### Steps to reproduce the behavior

1. [DEBUG] [11-13-23 10:30:33.338] Downloaded s5e25.jpg for "Can't Pay? We'll Take It Away! (2014)" from plex
2.[DEBUG] [11-13-23 10:30:47.738] Created card "/plex-tv/Can't Pay! We'll Take It Away! (2014)/Season 01/Can't Pay! We'll Take It Away! (2014) - S01E01 - Episode 1.jpg"
...

### Debug Log

[DEBUG] [11-13-23 10:30:33.338] Downloaded s5e25.jpg for "Can't Pay? We'll Take It Away! (2014)" from plex
[DEBUG] [11-13-23 10:30:47.738] Created card "/plex-tv/Can't Pay! We'll Take It Away! (2014)/Season 01/Can't Pay! We'll Take It Away! (2014) - S01E01 - Episode 1.jpg"

**Comment by CollinHeist** [comment]
Hey @TechJedi51 - I generally recommend just using a card directory (and it is required in v2) so that any folder name mismatches between TCM and your media folders are irrelevant. Because that's an option, and TCM still works as expected when the folder names don't match, I probably will not change this behavior.

**Comment by TechJedi51** [comment]
Cool. That will work.

**Comment by CollinHeist** [comment]
Let me know if there are any issues! Thanks
