### ISSUE TITLE
HELP - Can't Generate Title Cards

### ISSUE THREAD

**Issue by Alen3012** [CollinHeist/TitleCardMaker#436]
### Installation

GitHub - develop branch

### Describe your Problem

Currently using the web UI 2.0 beta. Every time I try to get generate a title card I get this: 

[WARNING] [dc71da9fbcf8] Card creation failed
[DEBUG] [dc71da9fbcf8] Command: convert "C:\Users\zoink\Downloads\Compressed\TitleCardMaker-WebUI-2.0-alpha.7.0\TitleCardMaker-WebUI-2.0-alpha.7.0\config\source\Malcolm in the Middle (2000)\s7e20.jpg" -sampling-factor 4:4:4 -set colorspace sRGB +profile "*" -background transparent -gravity center -resize "3200x1800^" -extent "3200x1800"   -set colorspace sRGB "C:\Users\zoink\Downloads\Compressed\TitleCardMaker-WebUI-2.0-alpha.7.0\TitleCardMaker-WebUI-2.0-alpha.7.0\modules\ref\GRADIENT.png" -composite -gravity south -font "C:\Users\zoink\Downloads\Compressed\TitleCardMaker-WebUI-2.0-alpha.7.0\TitleCardMaker-WebUI-2.0-alpha.7.0\modules\ref\Sequel-Neue.otf" -kerning -1.25 -interword-spacing 50 -interline-spacing -22 -pointsize 157.41 -fill "black" -stroke "black" -strokewidth 3.0 -annotate +0+245 "CATTLE COURT" -fill "#EBEBEB" -annotate +0+245 "CATTLE COURT" -background transparent -gravity center -kerning 5.42 -pointsize 67.75 -interword-spacing 14.5 \( -fill black -stroke black -strokewidth 6 -font "C:\Users\zoink\Downloads\Compressed\TitleCardMaker-WebUI-2.0-alpha.7.0\TitleCardMaker-WebUI-2.0-alpha.7.0\modules\ref\Proxima Nova Semibold.otf" label:"SEASON 7 •" -font "C:\Users\zoink\Downloads\Compressed\TitleCardMaker-WebUI-2.0-alpha.7.0\TitleCardMaker-WebUI-2.0-alpha.7.0\modules\ref\Proxima Nova Regular.otf" label:"EPISODE 20" +smush 25 \) -geometry +0+697.2 -composite \( -fill "#CFCFCF" -stroke "#CFCFCF" -strokewidth 0.75 -font "C:\Users\zoink\Downloads\Compressed\TitleCardMaker-WebUI-2.0-alpha.7.0\TitleCardMaker-WebUI-2.0-alpha.7.0\modules\ref\Proxima Nova Semibold.otf" label:"SEASON 7 •" -font "C:\Users\zoink\Downloads\Compressed\TitleCardMaker-WebUI-2.0-alpha.7.0\TitleCardMaker-WebUI-2.0-alpha.7.0\modules\ref\Proxima Nova Regular.otf" label:"EPISODE 20" +smush 30 \) -geometry +0+697.2 -composite -sampling-factor 4:4:4 -set colorspace sRGB +profile "*" -background transparent -gravity center -resize "3200x1800" -extent "3200x1800" "C:\Users\zoink\Downloads\Compressed\TitleCardMaker-WebUI-2.0-alpha.7.0\TitleCardMaker-WebUI-2.0-alpha.7.0\config\cards\Malcolm in the Middle (2000)\Season 7\Malcolm in the Middle (2000) - S07E20.jpg"

### Debug Log

<html>
<body>

Warning | 2024-02-06T17:41:23.354 | c5257febd9eb | Card creation failed
-- | -- | -- | --

</body>
</html>

**Comment by CollinHeist** [comment]
@Alen3012 Hey, so a few things:

1. This repo is for the non-UI (hence why the issue asks for YAML file snippets) - if you've got any other issues it'd be best to post those [here](https://github.com/TitleCardMaker/TitleCardMaker-WebUI)
2. When posting logs, if you could post the actual log files (`config/logs`), not a copy/paste from the log page. As you can see not much info is provided there.
3. As for the actual issue, did you install ImageMagick? I would recommend using Docker, as well. That comes with IM pre-installed,

**Comment by CollinHeist** [comment]
Oh and to add to this, another user had a similar issue and it was related to launching PowerShell as an admin. Are you doing that?

**Comment by CollinHeist** [comment]
I'm going to close this for now, please ping me and re-open if you are still having issues
