### ISSUE TITLE
setup

### ISSUE THREAD

**Issue by davetaste** [CollinHeist/TitleCardMaker#444]
### Installation

Docker - master tag

### Describe your Problem

docker build -t "titlecardmaker:latest" .  this gives me the following error  

The legacy builder is deprecated and will be removed in a future release. Install the buildx component to build images with BuildKit:

I'm in the right dir. I cant find an answer

### Preference File

```yaml
docker build -t "titlecardmaker:latest" .  this gives me the following error  


The legacy builder is deprecated and will be removed in a future release. Install the buildx component to build images with BuildKit:

I'm in the right dir. I cant find an answer
```

### Series YAML

```yaml
docker build -t "titlecardmaker:latest" .  this gives me the following error  


The legacy builder is deprecated and will be removed in a future release. Install the buildx component to build images with BuildKit:

I'm in the right dir. I cant find an answer
```

### Debug Log

docker build -t "titlecardmaker:latest" .  this gives me the following error  

The legacy builder is deprecated and will be removed in a future release. Install the buildx component to build images with BuildKit:

I'm in the right dir. I cant find an answer

**Comment by CollinHeist** [comment]
@davetaste You'll have to provide some more detail. What directory are you typing this in? Is this after you did the `git clone`? Did you update/re-install your Docker installation?

**Comment by davetaste** [comment]
Hi Colin

Using the Wiki,
https://titlecardmaker.com/getting_started/

 I've done everything up until this point

Launching the Interface
 Docker Non-Docker

   1.

   Build the Docker image under the tag titlecardmaker:latest, by executing
   the following command:
    Linux MacOS Windows (Powershell) Windows (Non-Powershell)

    <https://titlecardmaker.com/getting_started/#__codelineno-11-1>docker
build -t "titlecardmaker:latest" .


At this point it fails with the error.

Unriad CLI

Thanks,

Dan

**Comment by CollinHeist** [comment]
Okay thanks. It looks like your version of Docker is perhaps too old, it is not supporting the build requirements of the container. What version of Docker and Unraid are you running?

**Comment by davetaste** [comment]
Thanks Colin.

I've attached the release notes for the Unraid build. It's the latest
version.

I created the dir

Pulled from github.

It downloaded the files from github and put them in the directory.

I go back into cli.

Try and pull image.

Errors with the error.



Thanks

Dan.

**Comment by CollinHeist** [comment]
I don't see any attachments - and I'm guessing the Docker version is more important than the OS version. What's your docker version (`docker --version`)?

A quick [search](https://duckduckgo.com/?q=Install+the+buildx+component+to+build+images+with+BuildKit&ia=web) online shows some potential solutions for all OS's - [here](https://forums.unraid.net/topic/155522-can-no-longer-build-docker-images-after-update-to-6128/) is one for Unraid specifically.

**Comment by davetaste** [comment]
Thanks,

I can't get it to work. Can't get past this error. I'll come back in a few
months. I had read both the links you sent before making contact. I've
never actually reached out to anyone before or asked a question in a forum,
I usually find my answer by looking, but I can't find the answer to this.


Thanks,


Dan.

**Comment by davetaste** [comment]
I've just had a look at the Discord and it looks like people asking
questions and no one answering them. That's Discord in general though, to
me it always looks a bit of a mess

**Comment by davetaste** [comment]
***@***.***:~#  cd /mnt/user/appdata/titlecardmaker
***@***.***:/mnt/user/appdata/titlecardmaker# docker build -t
"titlecardmaker"
DEPRECATED: The legacy builder is deprecated and will be removed in a
future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/

"docker build" requires exactly 1 argument.
See 'docker build --help'.

Usage:  docker build [OPTIONS] PATH | URL | -

Build an image from a Dockerfile
***@***.***:/mnt/user/appdata/titlecardmaker#

**Comment by davetaste** [comment]
***@***.***:~# # syntax=docker/dockerfile:1
FROM docker
COPY --from=docker/buildx-bin /buildx
/usr/libexec/docker/cli-plugins/docker-buildx
RUN docker buildx version
bash: FROM: command not found
bash: COPY: command not found
bash: RUN: command not found
***@***.***:~# # Buildx 0.6+
$ docker buildx bake "https://github.com/docker/buildx.git"
$ mkdir -p ~/.docker/cli-plugins
$ mv ./bin/build/buildx ~/.docker/cli-plugins/docker-buildx

# Docker 19.03+
$ DOCKER_BUILDKIT=1 docker build --platform=local -o . "
https://github.com/docker/buildx.git"
$ mkdir -p ~/.docker/cli-plugins
$ mv buildx ~/.docker/cli-plugins/docker-buildx

# Local
$ git clone https://github.com/docker/buildx.git && cd buildx
$ make install
bash: $: command not found
bash: $: command not found
bash: $: command not found
bash: $: command not found
bash: $: command not found
bash: $: command not found
bash: $: command not found
bash: $: command not found
***@***.***:~# $ docker buildx bake "https://github.com/docker/buildx.git"
bash: $: command not found
***@***.***:~# $ docker run --name test --rm -it  -v
/var/run/docker.sock:/var/run/docker.sock \
  -v /usr/bin/docker:/usr/bin/docker -v
/usr/libexec/docker:/usr/libexec/docker  \
  -v /root:/root centos:7  /bin/bash
$ docker buildx ls
bash: $: command not found
bash: $: command not found
***@***.***:~#

**Comment by CollinHeist** [comment]
> ***@***.***:/mnt/user/appdata/titlecardmaker# docker build -t "titlecardmaker"

Is this the command you are running? I would check the docs again and triple check you are running the __exact__ commands; that should be `docker build -t "titlecardmaker:latest" .`

**Comment by davetaste** [comment]
It's copied and pasted from the wiki. I'll check it against the command
below.

Cheers

**Comment by davetaste** [comment]
Tried exactly as written, including the space and full stop.

Tried without the full stop and space

Screenshot attatched

**Comment by CollinHeist** [comment]
No attachments are included when you respond via email, can you try uploading them from the GitHub website?

**Comment by davetaste** [comment]
Attachments are being attached from my end as I can see it in the sent
items that the email was sent with an attachment.

**Comment by davetaste** [comment]
![Screenshot_20240316-000006.png](https://github.com/CollinHeist/TitleCardMaker/assets/115738446/b3c13655-6ccf-4e1e-82da-2324c1e06121)

**Comment by davetaste** [comment]
![DS.png](https://github.com/CollinHeist/TitleCardMaker/assets/115738446/9f6e0d80-d5a7-4040-b739-97923e5c65e2)

**Comment by CollinHeist** [comment]
There we go, thanks 👍🏻 

I can see in the first command (the one ending in `.`) that you are not in the installed TCM directory. You need to `cd` into and run commands in whatever directory you cloned TCM into, most likely `/mnt/user/appdata/titlecardmaker/TitleCardMaker-WebUI`.

**Comment by davetaste** [comment]
Thanks Colin.
I had read it as the main installation directory as /mnt/user/appdata/titlecardmaker

and went back to that after creating this

enter your account Username and the PAT from Step 2. The TCM code will now be downloaded into a **_subdirectory_** named TitleCardMaker-WebUI. 

Here the directory is referred to as  a sub directory 

and  a couple of steps below it is referred to as the main installation directory

Navigate to the installation directory within the command line.



Within the main installation directory, create the required folder for TCM - this is config - by executing the following command:

It was my mis-reading of what the sub and main dir were. The buildx error was a red herring as there was no buildx error when in the correct dir which made me think it was a docker issue.


Thanks for your time,

**Comment by CollinHeist** [comment]
Yeah that is a bit confusing, and classic Docker not giving helpful errors like "Hey there's no Dockerfile, maybe check somewhere else!" 👎🏻 

Glad we got it figured out. Let me know if you have any other issues, I'll close this for now
