### ISSUE TITLE
Auto Hide Season Title for Shows with only 1 Season

### ISSUE THREAD

**Issue by reyalsyffub** [CollinHeist/TitleCardMaker#446]
**Is your feature request related to a problem? Please describe.**
There is only an option to either set Season Titles to On or Off. I usually prefer them off for shows with only 1 season and on for all others.

**Describe the solution you'd like**
A 3rd option at a global/template level to default to "Show Season Titles for Shows with more than 1 Season" or similar

**Describe alternatives you've considered**
I'm currently manually setting it, which is find but cumbersome with a large library...

**Additional context**
A similar setting exists in Plex, whereby you only get the Season selector if there are multiple seasons, hence the thought.

**Comment by CollinHeist** [comment]
@reyalsyffub This is actually already implemented, it's just not documented very well because it doesn't interact very well with archives. Try:
```yaml
seasons:
  hide: auto
```

**Comment by CollinHeist** [comment]
I'm going to close this for now, feel free to re-open if you have any other issues or questions 👍🏻
