### ISSUE TITLE
HELP - Tautulli integration - Error reading update list, skipping and deleting

### ISSUE THREAD

**Issue by kvalle22** [CollinHeist/TitleCardMaker#453]
### Installation

GitHub - develop branch

### Describe your Problem

TCM is not creating cards with Tautulli integrations

### Screenshots

![image](https://github.com/CollinHeist/TitleCardMaker/assets/26128231/73f05a9e-f135-454c-972d-88356e2c98b5)
This is the directory where `update_card.cmd` is located

![image](https://github.com/CollinHeist/TitleCardMaker/assets/26128231/371b61a7-b68e-4813-9282-7aae5b3853ad)

This is my config on Tautulli
![image](https://github.com/CollinHeist/TitleCardMaker/assets/26128231/2518129d-145c-478b-924e-bf9ab01b8196)

I don't use the watched feature
![image](https://github.com/CollinHeist/TitleCardMaker/assets/26128231/2ac08928-9c9f-4fa3-9f45-3f58d51517e3)
![image](https://github.com/CollinHeist/TitleCardMaker/assets/26128231/fd54447a-bb6f-4a9c-acf2-9b26e0538d57)
![image](https://github.com/CollinHeist/TitleCardMaker/assets/26128231/e7598edc-fc4d-411e-9d57-4b2349619357)

### Preference File

```yaml
tautulli:
  url: http://localhost:8181/          # Your Tautulli URL
  api_key: ######################              # Your API key
  update_script: 'C:\Users\PMS\AppData\Local\Tautulli\config\update_card.cmd'
  verify_ssl: true
  username: kazeee
  agent_name: Update TitleCardMaker      # Your Username
  script_timeout: 120
```

### Debug Log

```
[INFO] [03-23-24 12:53:54.444] Sleeping until 12:54:54 2024-03-23
[DEBUG] [03-23-24 12:54:54.449] Update list does not exist
[INFO] [03-23-24 12:54:54.449] Sleeping until 12:55:54 2024-03-23
[DEBUG] [03-23-24 12:55:54.462] Update list does not exist
[INFO] [03-23-24 12:55:54.462] Sleeping until 12:56:54 2024-03-23
[DEBUG] [03-23-24 12:56:54.473] Update list does not exist
[INFO] [03-23-24 12:56:54.473] Sleeping until 12:57:54 2024-03-23
[INFO] [03-23-24 12:57:54.489] Read preference file "C:\Games\Plex\TitleCardMaker-develop-language2\preferences.yml"
[DEBUG] [03-23-24 12:57:54.652] Using "magick " ImageMagick command prefix
[ERROR] [03-23-24 12:57:54.652] Error reading update list, skipping and deleting
[INFO] [03-23-24 12:57:54.654] Sleeping until 12:58:54 2024-03-23
[DEBUG] [03-23-24 12:58:54.656] Update list does not exist
[INFO] [03-23-24 12:58:54.656] Sleeping until 12:59:54 2024-03-23
[DEBUG] [03-23-24 12:59:54.659] Update list does not exist
[INFO] [03-23-24 12:59:54.659] Sleeping until 13:00:54 2024-03-23
[DEBUG] [03-23-24 13:00:54.666] Update list does not exist
[INFO] [03-23-24 13:00:54.666] Sleeping until 13:01:54 2024-03-23
[DEBUG] [03-23-24 13:01:54.680] Update list does not exist
[INFO] [03-23-24 13:01:54.680] Sleeping until 13:02:54 2024-03-23
[DEBUG] [03-23-24 13:02:54.689] Update list does not exist
[INFO] [03-23-24 13:02:54.689] Sleeping until 13:03:54 2024-03-23
[DEBUG] [03-23-24 13:03:54.695] Update list does not exist
[INFO] [03-23-24 13:03:54.695] Sleeping until 13:04:54 2024-03-23
[DEBUG] [03-23-24 13:04:54.704] Update list does not exist
[INFO] [03-23-24 13:04:54.704] Sleeping until 13:05:54 2024-03-23
[DEBUG] [03-23-24 13:05:54.713] Update list does not exist
[INFO] [03-23-24 13:05:54.713] Sleeping until 13:06:54 2024-03-23
[DEBUG] [03-23-24 13:06:54.715] Update list does not exist
[INFO] [03-23-24 13:06:54.715] Sleeping until 13:07:54 2024-03-23
[DEBUG] [03-23-24 13:07:54.728] Update list does not exist
[INFO] [03-23-24 13:07:54.728] Sleeping until 13:08:54 2024-03-23
[DEBUG] [03-23-24 13:08:54.738] Update list does not exist
[INFO] [03-23-24 13:08:54.738] Sleeping until 13:09:54 2024-03-23
[DEBUG] [03-23-24 13:09:54.743] Update list does not exist
[INFO] [03-23-24 13:09:54.743] Sleeping until 13:10:54 2024-03-23
[DEBUG] [03-23-24 13:10:54.747] Update list does not exist
[INFO] [03-23-24 13:10:54.747] Sleeping until 13:11:54 2024-03-23
[DEBUG] [03-23-24 13:11:54.753] Update list does not exist
[INFO] [03-23-24 13:11:54.753] Sleeping until 13:12:54 2024-03-23
[INFO] [03-23-24 13:12:54.764] Read preference file "C:\Games\Plex\TitleCardMaker-develop-language2\preferences.yml"
[DEBUG] [03-23-24 13:12:54.795] Using "magick " ImageMagick command prefix
[ERROR] [03-23-24 13:12:54.795] Error reading update list, skipping and deleting
[INFO] [03-23-24 13:12:54.796] Sleeping until 13:13:54 2024-03-23

```

**Comment by kvalle22** [comment]
@CollinHeist 
This is what I'm putting inside the script `update_card.cmd`
`echo "$@" >> update.txt`
According to 
![image](https://github.com/CollinHeist/TitleCardMaker/assets/26128231/43c16567-b48a-404e-a899-9e1a3fa22b93)

**Comment by kvalle22** [comment]
![image](https://github.com/CollinHeist/TitleCardMaker/assets/26128231/1fe6366d-2406-4130-bcd5-eeb4a1215278)
and the resulting file looks like this 
![image](https://github.com/CollinHeist/TitleCardMaker/assets/26128231/d53fdc36-1727-4ebe-9491-2882f2acd974)

**Comment by CollinHeist** [comment]
@kvalle22 You will need to rewrite the script for Windows. Try
```cmd
@echo off
echo %* >> update.txt
```

**Comment by kvalle22** [comment]
oh yeah I was about to try that haha 
![image](https://github.com/CollinHeist/TitleCardMaker/assets/26128231/46f49748-b347-43dd-bcc7-008a3ad3d121)

**Comment by kvalle22** [comment]
@CollinHeist  what is `{rating_key}` or where can I find it for every show? I'll create it manually to test the script

**Comment by CollinHeist** [comment]
Did changing that work? Tautulli replaces `{rating_key}` with a number when it runs the script, so doing what you did before with `update_card.cmd 123` is equivalent

**Comment by kvalle22** [comment]
Yes the script now passes the info. But what I'm asking is what is rating key? is it the identifier for a show on TMDB? 
![image](https://github.com/CollinHeist/TitleCardMaker/assets/26128231/92422d56-6df0-48a7-bba4-ee5be7a395cc)
Or maybe TVDB?
![image](https://github.com/CollinHeist/TitleCardMaker/assets/26128231/db014f3d-1a0a-43a2-9043-1beccfd06e21)

**Comment by kvalle22** [comment]
![image](https://github.com/CollinHeist/TitleCardMaker/assets/26128231/f2e449f7-763b-452a-8010-721af954d818)
FOUND!

**Comment by CollinHeist** [comment]
Oh sorry, yeah they are essentially the "Plex ID" for how you can identify some content

**Comment by CollinHeist** [comment]
Do you have any more issues or questions? If not, feel free to close the issue 👍🏻

**Comment by kvalle22** [comment]
Oh yeah I completely forgot about it, thanks!!!!
