### ISSUE TITLE
Make docker container

### ISSUE THREAD

**Issue by CollinHeist** [CollinHeist/TitleCardMaker#67]
It would be convenient for cross-platform deployment (and dependency handling) to release the TitleCardMaker through Docker.

I know _literally_ nothing about how to do this, so I am actively looking for tips/resources/help on getting this done.

**Comment by KennethDenson** [comment]
This is literally what I'm waiting for....I've tried to do some research into how to do this, but it's beyond my capabilities in the meantime. Would love to see a docker compose file that would set up TCM and ImageMagick both take some of this config off my hands.

So I guess what I mean is....+1
