### ISSUE TITLE
Adding full stop between names.

### ISSUE THREAD

**Issue by elit3ge** [CollinHeist/TitleCardMaker#81]
When the card is created, it would be great if it could add a full stop between titles. eg. Slow Horses becomes Slow.Horses

**Comment by elit3ge** [comment]
Or given the ability to pull the file name from Sonarr and write it as that.

**Comment by CollinHeist** [comment]
I am working on having the Maker query Sonarr for filenames, and I think that will be a better solution than individual options for each possible naming scheme (such as periods between words).
