### ISSUE TITLE
Add option to change output file extension - add support for `.webp`

### ISSUE THREAD

**Issue by CollinHeist** [CollinHeist/TitleCardMaker#84]
Add global option to change extension to something other than jpg.

Probably like:

```yaml
options:
  card_extension: jpg
```

Could use `ImageMaker.VALID_IMAGE_EXTENSIONS` which is `('.jpg', '.jpeg', '.png', '.tiff', '.gif')`

**Comment by durmonator** [comment]
Hey @CollinHeist sorry to open this again, but I have thoroughly tested .webp and that works with Plex, also it is drastically smaller in size, retaining the same quality, would it be possible to add this in? Thanks

**Comment by CollinHeist** [comment]
@durmonator Sure, I didn't know Plex supported that format. I'll add that in the next version
